### ISSUE TITLE
feat: implement 0x15 - ISZERO opcode

### ISSUE THREAD

**Issue by jobez** [kkrt-labs/kakarot-ssj#10]
---
fork: Frontier
group: Comparison & Bitwise Logic Operations
---

*Index 1 is top of the stack. See [PUSH](https://www.evm.codes/#60).*

## Stack input

0. `a`: integer.

## Stack output

0. `a == 0`: 1 if `a` is 0, 0 otherwise.

## Examples

| * | Input | Output | * | * | Input | Output |
|--:|------:|-------:|--:|--:|------:|-------:|
| `1` | `10` | `0` | * | `1` | `0` | `1` |

[Reproduce in playground](https://www.evm.codes/playground?unit=Wei&codeType=Mnemonic&code='~1y1wzz~2yw'~%2F%2F%20Example%20z%5CnyzPUSH1%20w0zISZERO%01wyz~_).

## Error cases

The state changes done by the current context are [reverted](https://www.evm.codes/?fork=merge#FD) in those cases:
- Not enough values on the stack.

**Comment by dpinones** [comment]
I tried to implement what was specified in the issue but I had some doubts that I wrote in the code. Could you give me your opinion to know if I am on the right track. I leave the commit:
https://github.com/dpinones/kakarot-ssj/commit/a4877f8589fb00f8f8ca6f8f7de21247bbce8de3

**Comment by TAdev0** [comment]
@Eikix  may i implement this opcode?

**Comment by Noeljarillo** [comment]
I will love to implement this!

**Comment by danilowhk** [comment]
Assigned!

**Comment by Eikix** [comment]
Important update: we are gathering some bugs in the [Kakarot v0 codebase](https://github.com/kkrt-labs/kakarot), we need to make sure each issue and each PR in Kakarot-ssj is aware of the lists of known bugs. Look at [this tracking issue](https://github.com/kkrt-labs/kakarot-ssj/issues/324) everytime you take an issue and check your issue isn't targeted by a known bug. Will add this reminder in many places to make sure we keep track of known bugs.

**Comment by TAdev0** [comment]
@allcontributors please add @TAdev0 for code

**Comment by Eikix** [comment]
What is the status of this issue?
