### ISSUE TITLE
feat: implement 0x17 - OR opcode

### ISSUE THREAD

**Issue by jobez** [kkrt-labs/kakarot-ssj#12]
---
fork: Frontier
group: Comparison & Bitwise Logic Operations
---

*Index 1 is top of the stack. See [PUSH](https://www.evm.codes/#60).*

## Stack input

0. `a`: first binary value.
1. `b`: second binary value.

## Stack output

0. `a | b`: the bitwise OR result.

## Examples

| * | Input | Output | * | * | Input | Output |
|--:|------:|-------:|--:|--:|------:|-------:|
| `1` | `0xF0` | `0xFF` | * | `1` | `0xFF` | `0xFF` |
| `2` | `0xF` | | * | `2` | `0xFF` | |

[Reproduce in playground](https://www.evm.codes/playground?unit=Wei&codeType=Mnemonic&code='z1~~0yORyyz2~F~FyOR'~yPUSH1%200xFz%2F%2F%20Example%20y%5Cn%01yz~_).

## Error cases

The state changes done by the current context are [reverted](#FD) in those cases:
- Not enough values on the stack.

**Comment by TAdev0** [comment]
@Eikix  may i implement this opcode?

**Comment by Noeljarillo** [comment]
Will like to implement it!

**Comment by Eikix** [comment]
Important update: we are gathering some bugs in the [Kakarot v0 codebase](https://github.com/kkrt-labs/kakarot), we need to make sure each issue and each PR in Kakarot-ssj is aware of the lists of known bugs. Look at [this tracking issue](https://github.com/kkrt-labs/kakarot-ssj/issues/324) everytime you take an issue and check your issue isn't targeted by a known bug. Will add this reminder in many places to make sure we keep track of known bugs.
