### ISSUE TITLE
feat: implement 0x39 - CODECOPY Opcode

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-ssj#125]
<tr class="bg-indigo-50 dark:bg-black-600"><td colspan="6"><div class="text-sm px-4 md:px-8 py-8 bg-indigo-50 dark:bg-black-600"><table class="table-auto mb-6 bg-indigo-100 dark:bg-black-500 rounded font-medium"><thead><tr class="text-gray-500 uppercase text-xs tracking-wide"><td class="pt-3 px-4">Since</td><td class="pt-3 px-4">Group</td></tr></thead><tbody><tr><td class="pb-3 px-4">Frontier</td><td class="pb-3 px-4">Environmental Information</td></tr></tbody></table><div class="flex flex-col lg:flex-row"><div class="flex-1 lg:pr-8"><p class="leading-5 mb-4"><em>Index 1 is top of the stack. See <a class="underline" href="/#60">PUSH</a>.</em></p><h2 class="text-base font-semibold my-4">Notes</h2><p class="leading-5 mb-4">For out of bound bytes, 0s will be copied.</p><h2 class="text-base font-semibold my-4">Stack input</h2><ol class="list-decimal mb-4"><li class="ml-6"><code>destOffset</code>: byte offset in the <a class="underline" href="/about">memory</a> where the result will be copied.</li><li class="ml-6"><code>offset</code>: byte offset in the <a class="underline" href="/about">code</a> to copy.</li><li class="ml-6"><code>size</code>: byte size to copy.</li></ol><h2 class="text-base font-semibold my-4">Examples</h2><table class="table-auto mb-4"><thead><tr><th class="py-1 px-2 border-indigo-200 dark:border-black-400 text-gray-800 dark:text-gray-400 text-tiny font-medium break-all border">Code</th></tr></thead><tbody><tr><td class="py-1 px-2 border-indigo-200 dark:border-black-400 text-tiny font-normal break-all border"><code>0x7DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF7F</code></td></tr></tbody></table><table class="table-auto mb-4"><thead><tr><th class="py-1 px-2 border-indigo-200 dark:border-black-400 text-gray-800 dark:text-gray-400 text-tiny font-medium break-all"></th><th class="py-1 px-2 border-indigo-200 dark:border-black-400 text-gray-800 dark:text-gray-400 text-tiny font-medium break-all border">Input 1</th><th class="py-1 px-2 border-indigo-200 dark:border-black-400 text-gray-800 dark:text-gray-400 text-tiny font-medium break-all"></th><th class="py-1 px-2 border-indigo-200 dark:border-black-400 text-gray-800 dark:text-gray-400 text-tiny font-medium break-all"></th><th class="py-1 px-2 border-indigo-200 dark:border-black-400 text-gray-800 dark:text-gray-400 text-tiny font-medium break-all border">Input 2</th></tr></thead><tbody><tr><td class="py-1 px-2 border-indigo-200 dark:border-black-400 text-tiny font-normal break-all border"><code>1</code></td><td class="py-1 px-2 border-indigo-200 dark:border-black-400 text-tiny font-normal break-all border"><code>0</code></td><td class="py-1 px-2 border-indigo-200 dark:border-black-400 text-tiny font-normal break-all"></td><td class="py-1 px-2 border-indigo-200 dark:border-black-400 text-tiny font-normal break-all border"><code>1</code></td><td class="py-1 px-2 border-indigo-200 dark:border-black-400 text-tiny font-normal break-all border"><code>0</code></td></tr><tr><td class="py-1 px-2 border-indigo-200 dark:border-black-400 text-tiny font-normal break-all border"><code>2</code></td><td class="py-1 px-2 border-indigo-200 dark:border-black-400 text-tiny font-normal break-all border"><code>0</code></td><td class="py-1 px-2 border-indigo-200 dark:border-black-400 text-tiny font-normal break-all"></td><td class="py-1 px-2 border-indigo-200 dark:border-black-400 text-tiny font-normal break-all border"><code>2</code></td><td class="py-1 px-2 border-indigo-200 dark:border-black-400 text-tiny font-normal break-all border"><code>31</code></td></tr><tr><td class="py-1 px-2 border-indigo-200 dark:border-black-400 text-tiny font-normal break-all border"><code>3</code></td><td class="py-1 px-2 border-indigo-200 dark:border-black-400 text-tiny font-normal break-all border"><code>32</code></td><td class="py-1 px-2 border-indigo-200 dark:border-black-400 text-tiny font-normal break-all"></td><td class="py-1 px-2 border-indigo-200 dark:border-black-400 text-tiny font-normal break-all border"><code>3</code></td><td class="py-1 px-2 border-indigo-200 dark:border-black-400 text-tiny font-normal break-all border"><code>8</code></td></tr></tbody></table><table class="table-auto mb-4"><thead><tr><th class="py-1 px-2 border-indigo-200 dark:border-black-400 text-gray-800 dark:text-gray-400 text-tiny font-medium break-all border">Memory before</th></tr></thead><tbody><tr><td class="py-1 px-2 border-indigo-200 dark:border-black-400 text-tiny font-normal break-all border"><code>0</code></td></tr></tbody></table><table class="table-auto mb-4"><thead><tr><th class="py-1 px-2 border-indigo-200 dark:border-black-400 text-gray-800 dark:text-gray-400 text-tiny font-medium break-all border">Memory after input 1</th></tr></thead><tbody><tr><td class="py-1 px-2 border-indigo-200 dark:border-black-400 text-tiny font-normal break-all border"><code>0x7DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF7F</code></td></tr></tbody></table><table class="table-auto mb-4"><thead><tr><th class="py-1 px-2 border-indigo-200 dark:border-black-400 text-gray-800 dark:text-gray-400 text-tiny font-medium break-all border">Memory after input 1 then 2</th></tr></thead><tbody><tr><td class="py-1 px-2 border-indigo-200 dark:border-black-400 text-tiny font-normal break-all border"><code>0x7F00000000000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF7F</code></td></tr></tbody></table><p class="leading-5 mb-4"><a class="underline" href="https://www.evm.codes/playground?unit=Wei&amp;codeType=Mnemonic&amp;code=%27qPutwbeginning%20ofwcodXtowexpected%20valueZ30VxWWWWWZ32VyyqRemovewvalues%20fromwstackTTj1~32~0_j2~8~31_%27~Z1%20zFFFFFFy%5Cnw%20thXq%2F%2F%20jyyqExamplX_~0yCODECOPYZyPUSHXe%20WzzV%200TyPOP%01TVWXZ_jqwyz~_">Reproduce in playground</a>.</p><h2 class="text-base font-semibold my-4">Error cases</h2><p class="leading-5 mb-4">The state changes done by the current context are <a class="underline" href="/?fork=shanghai#FD">reverted</a> in those cases:</p><ul class="list-disc mb-2"><li class="ml-6">Not enough gas.</li><li class="ml-6">Not enough values on the stack.</li></ul><h2 class="text-base font-semibold my-4">Gas</h2><div><pre class="text-tiny inline-block whitespace-pre-wrap p-5 mb-4 bg-indigo-100 dark:bg-gray-800 rounded"><code>minimum_word_size = (size + 31) / 32

static_gas = 3
dynamic_gas = 3 * minimum_word_size + memory_expansion_cost
</code></pre></div><p class="leading-5 mb-4">The memory expansion cost explanation can be found <a class="underline" href="/about">here</a>.</p></div><div class="md:w-96"><div class="flex justify-between items-center"><h2 class="text-base font-semibold my-4">Estimate your gas cost</h2></div><div class="bg-indigo-100 dark:bg-black-500 p-4 rounded shadow"><div><label class="block text-sm text-gray-500 mb-1" for="offset">Input: destOffset</label><div class="flex items-center rounded px-3 py-2 bg-white/75 dark:bg-black-400/75 mb-4 text-sm font-mono"><input class="w-full outline-none bg-transparent dark:placeholder-black-400 text-sm" type="number" min="0" max="1000000000000" name="offset" value="0"></div></div><div><label class="block text-sm text-gray-500 mb-1" for="size">Input: size</label><div class="flex items-center rounded px-3 py-2 bg-white/75 dark:bg-black-400/75 mb-4 text-sm font-mono"><input class="w-full outline-none bg-transparent dark:placeholder-black-400 text-sm" type="number" min="0" max="1000000000000" name="size" value="0"></div></div><div><label class="block text-sm text-gray-500 mb-1" for="memorySize">State: current memory size</label><div class="flex items-center rounded px-3 py-2 bg-white/75 dark:bg-black-400/75 mb-4 text-sm font-mono"><input class="w-full outline-none bg-transparent dark:placeholder-black-400 text-sm" type="number" min="0" max="1000000000000" name="memorySize" value="0"></div></div><div class="flex items-center pt-2"><svg class="inline-block fill-current ri text-indigo-500 mr-2" style="width: 16px; height: 16px;"><use xlink:href="#remix_svg__ri-gas-station-fill"></use></svg>Static gas + dynamic gas = 3</div></div></div></div></div></td></tr>

**Comment by khaeljy** [comment]
I can work on this.
