### ISSUE TITLE
feat: assess migration path for the storage layout of EVM bytecode for EVM Smart Contracts in Kakarot

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-ssj#134]
# Feature Request

**Describe the Feature Request**

We are currently packing 16 bytes per 16 bytes for EVM SC on Cairo0 Kakarot.
We are exploring new ways of storing the bytecode for optimisation purposes.

Look at https://github.com/keep-starknet-strange/alexandria/blob/b5192458aaaf70782ce12311211f3302b7320cc3/src/storage/src/list.cairo#L4

**Comment by enitrat** [comment]
Will start working on a design doc for this

**Comment by Eikix** [comment]
Important update: we are gathering some bugs in the [Kakarot v0 codebase](https://github.com/kkrt-labs/kakarot), we need to make sure each issue and each PR in Kakarot-ssj is aware of the lists of known bugs. Look at this link everytime you take an issue and check your issue isn't targeted by a known bug.

**Comment by Eikix** [comment]
Important update: we are gathering some bugs in the [Kakarot v0 codebase](https://github.com/kkrt-labs/kakarot), we need to make sure each issue and each PR in Kakarot-ssj is aware of the lists of known bugs. Look at [this tracking issue](https://github.com/kkrt-labs/kakarot-ssj/issues/324) everytime you take an issue and check your issue isn't targeted by a known bug. Will add this reminder in many places to make sure we keep track of known bugs.

**Comment by Eikix** [comment]
Done by @enitrat in this last docs
