### ISSUE TITLE
feat: create pre-push hook updating gas snapshot file

### ISSUE THREAD

**Issue by enitrat** [kkrt-labs/kakarot-ssj#144]
# Feature Request

**Describe the Feature Request**
create a pre-push hook that runs the `scripts/gen_snapshot.py` script to update the `gas_snapshot.json` file with the current values
**Describe Preferred Solution**

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [x] Yes
- [ ] No

**Comment by enitrat** [comment]
@Eikix close and do #145 instead?

**Comment by Eikix** [comment]
I think this can be done in partnership with #145 since pre-push hook could run compare snapshot between curr and artifact's previous, and warn user of their gas metrics?

**Comment by enitrat** [comment]
something really nice would be to have the report available in the PRs so that reviewers can have a view of the impact of changes
