### ISSUE TITLE
feat: implement 0x1B - SHL opcode

### ISSUE THREAD

**Issue by jobez** [kkrt-labs/kakarot-ssj#15]
---
fork: Constantinople
group: Comparison & Bitwise Logic Operations
---

*Index 1 is top of the stack. See [PUSH](https://www.evm.codes/#60).*

## Notes

Shift the bits towards the most significant one. The bits moved after the 256th one are discarded, the new bits are set to 0.

## Stack input

0. `shift`: number of bits to shift to the left.
1. `value`: 32 bytes to shift.

## Stack output

0. `value << shift`: the shifted value. If `shift` is bigger than 255, returns 0.

## Examples

| * | Input | Output |
|--:|------:|-------:|
| `1` | `1` | `2` |
| `2` | `1` | |

| * | Input | Output |
|--:|------:|-------:|
| `1` | `4` | `0xF000000000000000000000000000000000000000000000000000000000000000` |
| `2` | `0xFF00000000000000000000000000000000000000000000000000000000000000` | |

[Reproduce in playground](https://www.evm.codes/playground?unit=Wei&codeType=Mnemonic&code='y1z1z1swwy2v32%200xFFuuuuutz4s'~tttzv1%20y%2F%2F%20Example%20w%5CnvwPUSHu~~t00swSHL%01stuvwyz~_).

## Error cases

The state changes done by the current context are [reverted](#FD) in those cases:
- Not enough values on the stack.

**Comment by trbutler4** [comment]
dibs

**Comment by danilowhk** [comment]
Assigned @trbutler4
