### ISSUE TITLE
feat: implement 0x1C - SHR opcode

### ISSUE THREAD

**Issue by jobez** [kkrt-labs/kakarot-ssj#16]
---
fork: Constantinople
group: Comparison & Bitwise Logic Operations
---

*Index 1 is top of the stack. See [PUSH](https://www.evm.codes/#60).*

## Notes

Shift the bits towards the least significant one. The bits moved before the first one are discarded, the new bits are set to 0.

## Stack input

0. `shift`: number of bits to shift to the right.
1. `value`: 32 bytes to shift.

## Stack output

0. `value >> shift`: the shifted value. If `shift` is bigger than 255, returns 0.

## Examples

| * | Input | Output | * | * | Input | Output |
|--:|------:|-------:|--:|--:|------:|-------:|
| `1` | `1` | `1` | * | `1` | `4` | `0xF` |
| `2` | `2` | | * | `2` | `0xFF` | |

[Reproduce in playground](https://www.evm.codes/playground?unit=Wei&codeType=Mnemonic&code='z1~2~1wyyz2~0xFF~4w'~yPUSH1%20z%2F%2F%20Example%20y%5CnwySHR%01wyz~_).

## Error cases

The state changes done by the current context are [reverted](https://www.evm.codes/?fork=merge#FD) in those cases:
- Not enough values on the stack.

**Comment by khaeljy** [comment]
@Eikix Can I implement this?
