### ISSUE TITLE
feat: implement 0x1D - SAR opcode

### ISSUE THREAD

**Issue by jobez** [kkrt-labs/kakarot-ssj#17]
---
fork: Constantinople
group: Comparison & Bitwise Logic Operations
---

*Index 1 is top of the stack. See [PUSH](https://www.evm.codes/#60).*

## Notes

Shift the bits towards the least significant one. The bits moved before the first one are discarded, the new bits are set to 0 if the previous most significant bit was 0, otherwise the new bits are set to 1.

## Stack input

0. `shift`: number of bits to shift to the right.
1. `value`: integer to shift.

## Stack output

0. `value >> shift`: the shifted value.

## Examples

| * | Input | Output |
|--:|------:|-------:|
| `1` | `1` | `1` |
| `2` | `2` | |

| * | Input | Output |
|--:|------:|-------:|
| `1` | `4` | `0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF` |
| `2` | `0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0` | |

[Reproduce in playground](https://www.evm.codes/playground?unit=Wei&codeType=Mnemonic&code='y1z2z1twwy2v32%200xuuu0z4t'~FFFFFFFzv1%20y%2F%2F%20Example%20w%5CnvwPUSHu~~~twSAR%01tuvwyz~_).

## Error cases

The state changes done by the current context are [reverted](https://www.evm.codes/?fork=merge#FD) in those cases:
- Not enough values on the stack.

**Comment by khaeljy** [comment]
@ClementWalter Can I do it?
