### ISSUE TITLE
feat: restore sub_context and calling_context fields in `ExecutionContext`

### ISSUE THREAD

**Issue by enitrat** [kkrt-labs/kakarot-ssj#177]
# Feature Request
Restore the  sub_context and calling_context fields in `ExecutionContext` struct. 
**Describe the Feature Request**
They're implemented implemented as nullable pointers, so wrapped inside a `Nullable<T>` struct.
**Describe Preferred Solution**

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [x] Yes
- [ ] No

**Comment by Eikix** [comment]
Important update: we are gathering some bugs in the [Kakarot v0 codebase](https://github.com/kkrt-labs/kakarot), we need to make sure each issue and each PR in Kakarot-ssj is aware of the lists of known bugs. Look at this link everytime you take an issue and check your issue isn't targeted by a known bug.

**Comment by Eikix** [comment]
Important update: we are gathering some bugs in the [Kakarot v0 codebase](https://github.com/kkrt-labs/kakarot), we need to make sure each issue and each PR in Kakarot-ssj is aware of the lists of known bugs. Look at [this tracking issue](https://github.com/kkrt-labs/kakarot-ssj/issues/324) everytime you take an issue and check your issue isn't targeted by a known bug. Will add this reminder in many places to make sure we keep track of known bugs.

**Comment by Eikix** [comment]
Closing this as we now have a different implementation for these fields
