### ISSUE TITLE
feat: derive `Default` where possible

### ISSUE THREAD

**Issue by enitrat** [kkrt-labs/kakarot-ssj#178]
# Feature Request
See new feature https://github.com/starkware-libs/cairo/pull/3935
**Describe the Feature Request**
We will use default derivation instead of custom implementations where possible.
**Describe Preferred Solution**

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [x] Yes
- [ ] No

**Comment by lambda-0x** [comment]
I think this is done with: https://github.com/kkrt-labs/kakarot-ssj/pull/231
