### ISSUE TITLE
feat(testing): Add ability to do smart contract call so certain opcodes can be tested

### ISSUE THREAD

**Issue by lambda-0x** [kkrt-labs/kakarot-ssj#183]
# Feature Request

**Describe the Feature Request**

for testing currently there is no way to test opcode logic inside a smart contract call.

For example:

`ADDRESS` opcode returns address of the immediate caller, so incase of nested smart contract calls its result will be different.

**Describe Preferred Solution**

not sure how smart contract deployment are handled, but afaik once we first need have support for [`sub_context`](https://github.com/kkrt-labs/kakarot-ssj/blob/a16aaec498b4488bc560f666943bb43da0771a8e/crates/evm/src/context.cairo#L172).

**Additional Context**

see: https://github.com/kkrt-labs/kakarot-ssj/pull/181#discussion_r1304512056

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [x] Yes
- [ ] No

**Comment by Eikix** [comment]
I think this is directly linked to the CALL opcode issue

**Comment by Eikix** [comment]
yes! good reasoning, we'll need all the infra that is present in the cairo0 codebase for calling between smart contracts
CALL
STATICCALL
DELEGATECALL
Contract Account abstraction

**Comment by Eikix** [comment]
Important update: we are gathering some bugs in the [Kakarot v0 codebase](https://github.com/kkrt-labs/kakarot), we need to make sure each issue and each PR in Kakarot-ssj is aware of the lists of known bugs. Look at this link everytime you take an issue and check your issue isn't targeted by a known bug.

**Comment by Eikix** [comment]
Important update: we are gathering some bugs in the [Kakarot v0 codebase](https://github.com/kkrt-labs/kakarot), we need to make sure each issue and each PR in Kakarot-ssj is aware of the lists of known bugs. Look at [this tracking issue](https://github.com/kkrt-labs/kakarot-ssj/issues/324) everytime you take an issue and check your issue isn't targeted by a known bug. Will add this reminder in many places to make sure we keep track of known bugs.
