### ISSUE TITLE
dev: move all constant powers (e.g. 256.pow(16) ) variables in utils, evm and memory into their own constants

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-ssj#185]
In the codebase, we have some power function that are applied to constants. let's move them to actual constants!

```[tasklist]
### Tasks
- [ ] Go through the codebase and find where we do apply pow, wrapping_pow, shift_left, shift_right, shift_left_wide, and shift_right_wide to constants
- [ ] Replace all these occurences by their actual value in the right type. You may use Python CLI to compute these values fast, even if they're u256!
```

**Comment by lambda-0x** [comment]
i can take this up

**Comment by lambda-0x** [comment]
i can take this up

**Comment by lambda-0x** [comment]
i can take this up

**Comment by Eikix** [comment]
we should wait a little bit until the codebase is stabilized

**Comment by Eikix** [comment]
Important update: we are gathering some bugs in the [Kakarot v0 codebase](https://github.com/kkrt-labs/kakarot), we need to make sure each issue and each PR in Kakarot-ssj is aware of the lists of known bugs. Look at this link everytime you take an issue and check your issue isn't targeted by a known bug.

**Comment by Eikix** [comment]
Important update: we are gathering some bugs in the [Kakarot v0 codebase](https://github.com/kkrt-labs/kakarot), we need to make sure each issue and each PR in Kakarot-ssj is aware of the lists of known bugs. Look at [this tracking issue](https://github.com/kkrt-labs/kakarot-ssj/issues/324) everytime you take an issue and check your issue isn't targeted by a known bug. Will add this reminder in many places to make sure we keep track of known bugs.

**Comment by enitrat** [comment]
@lambda-0x should be ready now

**Comment by lambda-0x** [comment]
on it
