### ISSUE TITLE
feat: Create generic `pow` implementation

### ISSUE THREAD

**Issue by enitrat** [kkrt-labs/kakarot-ssj#189]
# Feature Request
Create a generic implementation of `pow` over type `T` to avoid unnecessary code duplication. This will allow using all integer types in exponentiation operations.
This can not be performed natively for `wrapping_pow` as we can't use generics with libfuncs such as `u256_overflow_mul`. That would require adding a `WrappingMath` trait, but it's not a priority for now
**Describe the Feature Request**

**Describe Preferred Solution**

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [ ] Yes
- [ ] No

**Comment by Eikix** [comment]
Important update: we are gathering some bugs in the [Kakarot v0 codebase](https://github.com/kkrt-labs/kakarot), we need to make sure each issue and each PR in Kakarot-ssj is aware of the lists of known bugs. Look at this link everytime you take an issue and check your issue isn't targeted by a known bug.

**Comment by Eikix** [comment]
Important update: we are gathering some bugs in the [Kakarot v0 codebase](https://github.com/kkrt-labs/kakarot), we need to make sure each issue and each PR in Kakarot-ssj is aware of the lists of known bugs. Look at [this tracking issue](https://github.com/kkrt-labs/kakarot-ssj/issues/324) everytime you take an issue and check your issue isn't targeted by a known bug. Will add this reminder in many places to make sure we keep track of known bugs.

**Comment by Eikix** [comment]
Closing in favor of #408
