### ISSUE TITLE
refactor: refactor opcodes that end with `stack.push(some_value)?;` and `Result::Ok(())` into `stack.push(some_value)`

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-ssj#190]
Currently, when inside a function that returns a result, but manipulates result-based functions itself, we often bubble up errors and unwrap results using "?" operator.

This is useful if we want to do something with the result, if we just want to propagate it as is, e.g. `stack.push(some_value)?;` is on the pre-last line, then we could just do:
`stack.push(some_value)` ,thus returning the result itself!

**Comment by lambda-0x** [comment]
i can work on this
