### ISSUE TITLE
bug: Memory store_n straddling 2 words

### ISSUE THREAD

**Issue by khaeljy** [kkrt-labs/kakarot-ssj#199]
# Bug Report

**Kakarot version:** 

Current main branch (commit [f49c9ef](https://github.com/kkrt-labs/kakarot-ssj/commit/f49c9efdfed7753421aa2186d9c18d315c3bb230))

**Current behavior:**

I want to store a `Span<u8>` in memory straddling 2 words and at a start offset that is not the start of the first word.

For exemple: Store values `1` and `2` in offsets `15` and `16`

But it raises an error: `panicked with [155785504329508738615720351733824384887 ('u32_sub Overflow'), ]`

**Expected behavior:**

Memory offset `15` set to `1` and memory offset `16` set to `2`.

**Steps to reproduce:**

**Related code:**

```
let mut ctx = setup_execution_context();
ctx.memory.store_n(array![1,2].span(), 15);
```

**Other information:**

**Comment by enitrat** [comment]
looks to be related to this line

```
let aligned_bytes = elements
            .slice(
                16 - offset_in_chunk_i, elements.len() - 16 - offset_in_chunk_i - offset_in_chunk_f,
            );
```
