### ISSUE TITLE
feat: make chain_id a storage variable and set it in main contract constructor

### ISSUE THREAD

**Issue by Quentash** [kkrt-labs/kakarot-ssj#206]
# Feature Request

**Describe the Feature Request**

Currently, the chain_id is hardcoded as the constants 'KKRT' (0x4b4b5254) in ASCII.
We would like to make chain_id a storage variable and set it in the main contract constructor.

**Describe Preferred Solution**

Make chain_id a storage variable and set it in the main contract constructor.

**Comment by Eikix** [comment]
Important update: we are gathering some bugs in the [Kakarot v0 codebase](https://github.com/kkrt-labs/kakarot), we need to make sure each issue and each PR in Kakarot-ssj is aware of the lists of known bugs. Look at this link everytime you take an issue and check your issue isn't targeted by a known bug.

**Comment by Eikix** [comment]
Important update: we are gathering some bugs in the [Kakarot v0 codebase](https://github.com/kkrt-labs/kakarot), we need to make sure each issue and each PR in Kakarot-ssj is aware of the lists of known bugs. Look at [this tracking issue](https://github.com/kkrt-labs/kakarot-ssj/issues/324) everytime you take an issue and check your issue isn't targeted by a known bug. Will add this reminder in many places to make sure we keep track of known bugs.
