### ISSUE TITLE
implement EOA bytecode and bytecode_len

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-ssj#210]
```[tasklist]
### Tasks
- [x] write the bytecode() method, it returns an empty Span of u8
- [x] write the bytecode_len() method, it returns 0
```

Note:
We could also remove the bytecode_len() function, and just do Span.len() for the EXTCODE opcode,
But when we'll try to do EXTCODE on an Contract Account (EVM Smart Contract), bytecode will be split into many storage vars, so it's easier to just store the bytecode_len as its own storage var imo

Related code:
Cairo Zero codebase: 
https://github.com/kkrt-labs/kakarot/blob/0c6e7a62a38e973ad6ceebfbf648841749ffe0ee/src/kakarot/accounts/eoa/externally_owned_account.cairo#L125

**Comment by danilowhk** [comment]
I can take this issue
