### ISSUE TITLE
dev: implement Into<bool,u256> trait

### ISSUE THREAD

**Issue by enitrat** [kkrt-labs/kakarot-ssj#239]
which allows us to naturally do
```rust
let result:u256 = a.slt(b).into();
```
instead of 
```rust
let result = if (a.slt(b)) {
            1
        } else {
            0
        };
```

**Comment by khaeljy** [comment]
@enitrat Can I do it?

**Comment by enitrat** [comment]
yes, please implement it under utils::traits

**Comment by khaeljy** [comment]
Perhaps we should implement `Into<bool, u8>` instead, which would allow conversion to any integer size?

`BoolIntoU8::into(boolean_value).into()`

**Comment by enitrat** [comment]
I said Into<bool,u32> so that we could directly push the values to the stack, but I meant `Into<bool,u256>`. of course we could do all integer types but we don't need it right now
