### ISSUE TITLE
feat: implement 0x01 - ADD opcode

### ISSUE THREAD

**Issue by jobez** [kkrt-labs/kakarot-ssj#24]
---
fork: Frontier
group: Stop and Arithmetic Operations
---

*Index 1 is top of the stack. See [PUSH](https://www.evm.codes/#60).*

## Stack input

0. `a`: first integer value to add.
1. `b`: second integer value to add.

## Stack output

0. `a + b`: integer result of the addition modulo 2<sup>256</sup>.

## Examples

| * | Input | Output | * | * | Input | Output |
|--:|------:|-------:|--:|--:|------:|-------:|
| `1` | `10` | `20` | * | `1` | `0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF` | `0` |
| `2` | `10` | | * | `2` | `1` | |

[Reproduce in playground](https://www.evm.codes/playground?unit=Wei&codeType=Mnemonic&code='y1z0z0twwy2v32%200xsssszt'~uuuuzv1%201y%2F%2F%20Example%20w%5CnvwPUSHuFFtwADDs~~%01stuvwyz~_).

## Error cases

The state changes done by the current context are [reverted](https://www.evm.codes/?fork=merge#FD) in those cases:
- Not enough values on the stack.

**Comment by greged93** [comment]
Did some work on this issue https://github.com/greged93/kakarot-ssj/commit/7c55d085a64a4499eb6c6b138542d6921e5cb3ea but getting some error:
```
Failed to specialize: `dup<kakarot::context::ExecutionContext>` error
```
Any help to debug would be appreciated.
