### ISSUE TITLE
feat: implement 0x51 - MLOAD Opcode

### ISSUE THREAD

**Issue by khaeljy** [kkrt-labs/kakarot-ssj#242]
# Feature Request

| Since | Group |
| --- | --- |
| Frontier| Stack Memory Storage and Flow Operations |

*Index 1 is top of the stack. See [PUSH](https://www.evm.codes/#60).*

## Stack input

1.  `offset`: offset in the [memory](https://www.evm.codes/about) in bytes.

## Stack output

1.  `value`: the 32 bytes in [memory](https://www.evm.codes/about) starting at that offset. If it goes beyond its current size (see [MSIZE](https://www.evm.codes/#59)), writes 0s.

## Examples

| Memory |
|-------|
| `0x00000000000000000000000000000000000000000000000000000000000000FF` |

|  | Input | Output |  |  | Input | Output |
|--:|------:|-------:|--:|--:|------:|-------:|
| `1` | `0` | `0xFF` |  | `1` | `1` | `0xFF00` |

[Reproduce in playground](https://www.evm.codes/playground?unit=Wei&codeType=Mnemonic&code='qPut%20thkstatkin%20memoryg32%200xfffffdFFv0zMSTOREw1v0jw2v1jz'~dddz%5CnwzzqExamplkvg1%20q%2F%2F%20ke%20jzMLOADgzPUSHf~~d00%01dfgjkqvwz~_).

## Error cases

The state changes done by the current context are [reverted](#FD) in those cases:
- Not enough gas.
- Not enough values on the stack.

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [x] Yes

```[tasklist]
### Tasks
- [ ] https://github.com/kkrt-labs/kakarot-ssj/issues/245
- [ ] After #245 is implemented, go and implement the business logic of MLOAD
```

**Comment by khaeljy** [comment]
@Eikix Can you assign me, pls?

**Comment by Eikix** [comment]
Important update: we are gathering some bugs in the [Kakarot v0 codebase](https://github.com/kkrt-labs/kakarot), we need to make sure each issue and each PR in Kakarot-ssj is aware of the lists of known bugs. Look at this link everytime you take an issue and check your issue isn't targeted by a known bug.

**Comment by Eikix** [comment]
Important update: we are gathering some bugs in the [Kakarot v0 codebase](https://github.com/kkrt-labs/kakarot), we need to make sure each issue and each PR in Kakarot-ssj is aware of the lists of known bugs. Look at [this tracking issue](https://github.com/kkrt-labs/kakarot-ssj/issues/324) everytime you take an issue and check your issue isn't targeted by a known bug. Will add this reminder in many places to make sure we keep track of known bugs.
