### ISSUE TITLE
feat: implement 0x52 - MSTORE Opcode

### ISSUE THREAD

**Issue by khaeljy** [kkrt-labs/kakarot-ssj#243]
# Feature Request

| Since | Group |
| --- | --- |
| Frontier| Stack Memory Storage and Flow Operations |

*Index 1 is top of the stack. See [PUSH](https://www.evm.codes/#60).*

## Stack input

1. `offset`: offset in the [memory](https://www.evm.codes/about) in bytes.
2. `value`: 32-byte value to write in the [memory](https://www.evm.codes/about).

## Examples

|  | Input 1 |  |  | Input 2 |
|--:|--------:|--:|--:|--------:|
| `1` | `0` |  | `1` | `1` |
| `2` | `0xFF` |  | `2` | `0xFF` |

| Memory before |
|--------------|
| `0` |

| Memory after input 1 |
|---------------------|
| `0x00000000000000000000000000000000000000000000000000000000000000FF` |

| Memory after input 1 then 2 |
|----------------------------|
| `0x0000000000000000000000000000000000000000000000000000000000000000FF` |

[Reproduce in playground](https://www.evm.codes/playground?unit=Wei&codeType=Mnemonic&code='z1v0wyz2v1w'~yPUSH1%20z%2F%2F%20Example%20y%5CnwyMSTOREyv~0xFF~%01vwyz~_).

## Error cases

The state changes done by the current context are [reverted](#FD) in those cases:
- Not enough gas.
- Not enough values on the stack.

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [x] Yes

```[tasklist]
### Tasks
- [ ] #247
- [ ] After #247 is implemented, go and implement the business logic of MSTORE
```

**Comment by khaeljy** [comment]
@Eikix Can you assign me, pls?

**Comment by Eikix** [comment]
Important update: we are gathering some bugs in the [Kakarot v0 codebase](https://github.com/kkrt-labs/kakarot), we need to make sure each issue and each PR in Kakarot-ssj is aware of the lists of known bugs. Look at this link everytime you take an issue and check your issue isn't targeted by a known bug.

**Comment by Eikix** [comment]
Important update: we are gathering some bugs in the [Kakarot v0 codebase](https://github.com/kkrt-labs/kakarot), we need to make sure each issue and each PR in Kakarot-ssj is aware of the lists of known bugs. Look at [this tracking issue](https://github.com/kkrt-labs/kakarot-ssj/issues/324) everytime you take an issue and check your issue isn't targeted by a known bug. Will add this reminder in many places to make sure we keep track of known bugs.
