### ISSUE TITLE
feat: implement 0x57 - JUMPI Opcode

### ISSUE THREAD

**Issue by khaeljy** [kkrt-labs/kakarot-ssj#252]
# Feature Request

| Since | Group |
| --- | --- |
| Frontier| Stack Memory Storage and Flow Operations |

*Index 1 is top of the stack. See [PUSH](https://www.evm.codes//#60).*

## Notes

The program counter (PC) is a byte offset in the deployed [code](https://www.evm.codes/about). It indicates which instruction will be executed next. When an [ADD](https://www.evm.codes/#01) is executed, for example, the PC is incremented by 1, since the instruction is 1 byte. The [PUSH](https://www.evm.codes/#60) instructions are bigger than one byte, and so will increment the counter accordingly.

The **JUMPI** instruction may alter the program counter, thus breaking the linear path of the execution to another point in the deployed [code](https://www.evm.codes/about). It is used to implement functionalities like loops and conditions.

## Stack input

1. `counter`: byte offset in the deployed [code](https://www.evm.codes/about) where execution will continue from. Must be a [JUMPDEST](https://www.evm.codes/#5B) instruction.
1. `b`: the program counter will be altered with the new value only if this value is different from 0. Otherwise, the program counter is simply incremented and the next instruction will be executed.

## Example

[See in playground](https://www.evm.codes/playground?unit=Wei&codeType=Mnemonic&code='qFirstk%20noYjump%2C%20secondkw0%20XRY0w10z2~h4~W_z5w12z7~h9~Z0gINVALIDK11gZ2w_z13'~%20%7Bprevious%20instruction%20occupiR%202%20bytR%7DgzXseYwgWq%2F%2F%20k%20example%20doRhQI%20%20Kg%5Cn_1%20ZQDESTz1Yt%20X%20qOffWPUSH_ResQJUMPK%20z%01KQRWXYZ_ghkqwz~_).

## Error cases

The state changes done by the current context are [reverted](#FD) in those cases:
- Not enough gas.
- Not enough values on the stack.
- `Counter` offset is not a [JUMPDEST](https://www.evm.codes/#5B). The error is generated only if the JUMP would have been done.
```[tasklist]
### Tasks
- [ ] https://github.com/kkrt-labs/kakarot-ssj/issues/253
- [ ] After #253 is implemented, go and implement the business logic of JUMPI
```

**Comment by lambda-0x** [comment]
will pick up this after #250 as they are closely related.

**Comment by Eikix** [comment]
Important update: we are gathering some bugs in the [Kakarot v0 codebase](https://github.com/kkrt-labs/kakarot), we need to make sure each issue and each PR in Kakarot-ssj is aware of the lists of known bugs. Look at this link everytime you take an issue and check your issue isn't targeted by a known bug.

**Comment by Eikix** [comment]
Important update: we are gathering some bugs in the [Kakarot v0 codebase](https://github.com/kkrt-labs/kakarot), we need to make sure each issue and each PR in Kakarot-ssj is aware of the lists of known bugs. Look at [this tracking issue](https://github.com/kkrt-labs/kakarot-ssj/issues/324) everytime you take an issue and check your issue isn't targeted by a known bug. Will add this reminder in many places to make sure we keep track of known bugs.

**Comment by lambda-0x** [comment]
can someone assign this to me please
