### ISSUE TITLE
feat: implement 0x5B - JUMPDEST Opcode

### ISSUE THREAD

**Issue by khaeljy** [kkrt-labs/kakarot-ssj#260]
# Feature Request

| Since | Group |
| --- | --- |
| Frontier| Stack Memory Storage and Flow Operations |

## Notes

Mark a valid destination for [JUMP](https://www.evm.codes/#56) or [JUMPI](https://www.evm.codes/#57). This operation has no effect on machine state during execution.
```[tasklist]
### Tasks
- [ ] https://github.com/kkrt-labs/kakarot-ssj/issues/261
- [ ] After #261 is implemented, go and implement the business logic of JUMPDEST
```

**Comment by lambda-0x** [comment]
will pick up this after #250 as they are closely related.

**Comment by Eikix** [comment]
Important update: we are gathering some bugs in the [Kakarot v0 codebase](https://github.com/kkrt-labs/kakarot), we need to make sure each issue and each PR in Kakarot-ssj is aware of the lists of known bugs. Look at this link everytime you take an issue and check your issue isn't targeted by a known bug.

**Comment by Eikix** [comment]
Important update: we are gathering some bugs in the [Kakarot v0 codebase](https://github.com/kkrt-labs/kakarot), we need to make sure each issue and each PR in Kakarot-ssj is aware of the lists of known bugs. Look at [this tracking issue](https://github.com/kkrt-labs/kakarot-ssj/issues/324) everytime you take an issue and check your issue isn't targeted by a known bug. Will add this reminder in many places to make sure we keep track of known bugs.

**Comment by lambda-0x** [comment]
@Eikix jumpdesk is a just a marker and it doesn't affect the execution state in anyway (essentially a noop). So do we need to do anything here like adding comment on `exec_jumpdest` or should this be closed?

**Comment by Eikix** [comment]
> @Eikix jumpdesk is a just a marker and it doesn't affect the execution state in anyway (essentially a noop). So do we need to do anything here like adding comment on `exec_jumpdest` or should this be closed?

can you check what execution specs does?

**Comment by lambda-0x** [comment]
yes i checked, it just increments pc and charge gas:

- [execution spec](https://github.com/ethereum/execution-specs/blob/e69b38986263fb1cdaf1331f05b7eacc6c9cd8ff/src/ethereum/shanghai/vm/instructions/control_flow.py#L149-L171)
- [geth](https://github.com/ethereum/go-ethereum/blob/48fdb79de5a3dc02be1c44479247515275b8b76a/core/vm/instructions.go#L557-L559)
- [kakarot cairo 0](https://github.com/kkrt-labs/kakarot/blob/7f8d856fb0016a02612bb15dc03e3dba9b3fc646/src/kakarot/instructions/memory_operations.cairo#L258-L269)

**Comment by Eikix** [comment]
> yes i checked, it just increments pc and charge gas:
> 
> 
> 
> - [execution spec](https://github.com/ethereum/execution-specs/blob/e69b38986263fb1cdaf1331f05b7eacc6c9cd8ff/src/ethereum/shanghai/vm/instructions/control_flow.py#L149-L171)
> 
> - [geth](https://github.com/ethereum/go-ethereum/blob/48fdb79de5a3dc02be1c44479247515275b8b76a/core/vm/instructions.go#L557-L559)
> 
> - [kakarot cairo 0](https://github.com/kkrt-labs/kakarot/blob/7f8d856fb0016a02612bb15dc03e3dba9b3fc646/src/kakarot/instructions/memory_operations.cairo#L258-L269)

then let's have it do just that

**Comment by lambda-0x** [comment]
PC is incremented automatically and we are not doing gas logic here. will open a PR to add comment saying explicitly its no op for clarity.

**Comment by Eikix** [comment]
> PC is incremented automatically and we are not doing gas logic here. So logic wise there is nothing to do here. Will open a PR to add comment saying explicitly its no op for clarity.

I think we're doing something wrong then, I believe opcodes should increment the pc themselves, at least that's how it is done in EELS, as push_n increases pc by 1 + n

Let's open an issue and propose a new way to handle PC incrementation, wdyt @enitrat and @lambda-0x

**Comment by lambda-0x** [comment]
hmm i don't think its necessarily wrong, its just matter of how the code is structured.

for `PUSH_N` instructions the first (`1`) increment of PC is done by `decode_and_execute` method and `n` is incremented by `read_code` method in `ExecutionContext` (which we call in `exec_push_n`). So as far as implementation uses proper methods PC should be properly incremented everytime.
