### ISSUE TITLE
feat: implement 0x50 - POP Opcode

### ISSUE THREAD

**Issue by khaeljy** [kkrt-labs/kakarot-ssj#262]
# Feature Request

| Since | Group |
| --- | --- |
| Frontier| Stack Memory Storage and Flow Operations |

*Index 1 is top of the stack. See [PUSH](https://www.evm.codes/#60).*

## Stack input

1. `y`: a stack item.

## Example

|  | Input | Output |
|--|------|-------|
| `1` | `125985` | |

[Reproduce in playground](https://www.evm.codes/playground?unit=Wei&codeType=Mnemonic&code='PUSH3%20125985%5CnPOP'_).

## Error cases

The state changes done by the current context are [reverted](https://www.evm.codes/#FD) in those cases:
- Not enough gas.
- Not enough values on the stack.
```[tasklist]
### Tasks
- [ ] https://github.com/kkrt-labs/kakarot-ssj/issues/263
- [ ] After #263 is implemented, go and implement the business logic of POP
```

**Comment by Quentash** [comment]
Can I have this one please ?
