### ISSUE TITLE
bug: Memory store_n errors

### ISSUE THREAD

**Issue by khaeljy** [kkrt-labs/kakarot-ssj#275]
# Bug Report

**Kakarot version:**
main

**Current behavior:**
I get several errors when I try to store data in memory.

This case causes an `Index out of bounds` error:
```
let mut ctx = setup_execution_context();
ctx.memory.store_n(array![1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30].span(), 3);
```

This case causes an `u32_sub Overflow` error:
```
let mut ctx = setup_execution_context();
ctx.memory.store_n(array![1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23].span(), 10);
```

**Expected behavior:**

Memory should be updated.

**Steps to reproduce:**

**Related code:**

```
fn test_store_n() {
    let mut ctx = setup_execution_context();
    ctx.memory.store_n(array![1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30].span(), 3); // ('Index out of bounds')
    ctx.memory.store_n(array![1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23].span(), 10); // ('u32_sub Overflow')
}
```

**Comment by Eikix** [comment]
Important update: we are gathering some bugs in the [Kakarot v0 codebase](https://github.com/kkrt-labs/kakarot), we need to make sure each issue and each PR in Kakarot-ssj is aware of the lists of known bugs. Look at this link everytime you take an issue and check your issue isn't targeted by a known bug.

**Comment by Eikix** [comment]
Important update: we are gathering some bugs in the [Kakarot v0 codebase](https://github.com/kkrt-labs/kakarot), we need to make sure each issue and each PR in Kakarot-ssj is aware of the lists of known bugs. Look at [this tracking issue](https://github.com/kkrt-labs/kakarot-ssj/issues/324) everytime you take an issue and check your issue isn't targeted by a known bug. Will add this reminder in many places to make sure we keep track of known bugs.

**Comment by enitrat** [comment]
@khaeljy Is this still occuring? I could not reproduce

```rust

#[test]
#[available_gas(200000000)]
fn test_store_n() {
     let mut memory = MemoryTrait::new();
    memory.store_n(array![1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30].span(), 3); // ('Index out of bounds')
    memory.store_n(array![1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23].span(), 10); // ('u32_sub Overflow')
}

```

works

**Comment by khaeljy** [comment]
Yes, it seems to have been fixed! 👍

**Comment by enitrat** [comment]
Nice !
