### ISSUE TITLE
dev: check if pad_zeroes would cost more than calling `store_n` twice

### ISSUE THREAD

**Issue by enitrat** [kkrt-labs/kakarot-ssj#278]
In {calldata/returndata/code}copy opcodes, we call the `store_n` function twice to store first the data copied and then the out-of-bounds bytes represented by zeroes. 

We have to check whether padding the copied data (which involves an explicit clone) is more optimized or not, for different array sizes

**Comment by Eikix** [comment]
Since you opened https://github.com/kkrt-labs/kakarot-ssj/pull/277, does that mean that `pad_zeroes` would cost less than calling store_n twice

**Comment by enitrat** [comment]
@Eikix yes but only for small array sizes from what I've seen. The goal of this issue is to determine whether this still holds for different array sizes and if not what the inflexion point is

**Comment by Eikix** [comment]
Important update: we are gathering some bugs in the [Kakarot v0 codebase](https://github.com/kkrt-labs/kakarot), we need to make sure each issue and each PR in Kakarot-ssj is aware of the lists of known bugs. Look at this link everytime you take an issue and check your issue isn't targeted by a known bug.

**Comment by Eikix** [comment]
Important update: we are gathering some bugs in the [Kakarot v0 codebase](https://github.com/kkrt-labs/kakarot), we need to make sure each issue and each PR in Kakarot-ssj is aware of the lists of known bugs. Look at [this tracking issue](https://github.com/kkrt-labs/kakarot-ssj/issues/324) everytime you take an issue and check your issue isn't targeted by a known bug. Will add this reminder in many places to make sure we keep track of known bugs.

**Comment by enitrat** [comment]
Closed with #343
