### ISSUE TITLE
bug: Memory expansion should only increments modulo 32

### ISSUE THREAD

**Issue by khaeljy** [kkrt-labs/kakarot-ssj#283]
# Bug Report

**Kakarot version:**
main

**Current behavior:**
Memory expansion is not by increments modulo 32.

**Expected behavior:**
Memory expansion should only increments modulo 32. ([playground](https://www.evm.codes/playground?fork=shanghai&unit=Wei&codeType=Mnemonic&code='jInitiallyhkufirst~1mkx21upart%20ofgecond~2ms'~mqPOPqjNowgize%20is%20v%20%2F%2F%20uqMLOADvRead%20q%5Cnm%20wordkqPUSH1hjMSIZEvh%200g%20s%01ghjkmquv~_))

**Steps to reproduce:**
By initializing the memory, then expanding the memory by 1, the new size should be 64 bytes, not 33 bytes.

**Related code:**

```
// Given
let mut memory = MemoryTrait::new();
let value: u256 = 1;
let bytes_array = helpers::u256_to_bytes_array(value);

memory.store_n(bytes_array.span(), 0);

// When
let cost = memory.expand(1);

// Then
assert(cost >= 0, 'cost should be positive');
assert(memory.bytes_len == 64, 'memory should be 64bytes');
let value = memory.load_internal(0);
assert(value == 1, 'value should be 1');
```

**Comment by khaeljy** [comment]
I can take this

**Comment by Eikix** [comment]
Hi, thanks for the bug report!
I think there might be a misunderstanding. 

Because MLOAD loads a word that is 32 bytes long, it'll expand at the same time of loading the word, thus expanding 32 bytes per 32 bytes.

You can try with other opcodes that can trigger memory expansion, such as SHA3, and try in a way that is not modulo 32 for reference.

**Comment by khaeljy** [comment]
MLOAD does indeed load 32 bytes, but not necessarily whole words. We can load 32 bytes from offset 1, which must extend memory by 32 bytes.

I've done the exercise with SHA3, loading 33 bytes into memory should expand it by 32 bytes.

See [playground](https://www.evm.codes/playground?fork=shanghai&unit=Wei&codeType=Mnemonic&code='kPutjrequired%20valubin%20memoryf32%200xFFFFFFFF____w0~MSTORE~g~~kCalljopcodew4s~w33s'~%5Cnz0000000wf1%20sw0~SHA3gk%2F%2F%20j%20thbg~MSIZEf~PUSHbe%20_zz%01_bfgjkswz~_).

**Comment by Eikix** [comment]
Thanks for the shoutout, found the official Ethereum spec, implemented in Python
We're starting to look into it for clear guidelines on such edge cases:
https://github.com/ethereum/execution-specs/blob/master/src/ethereum/shanghai/vm/gas.py#L142
