### ISSUE TITLE
feat: remove all legacy gas costs calculations

### ISSUE THREAD

**Issue by enitrat** [kkrt-labs/kakarot-ssj#288]
# Feature Request
The direction we're taking in the EVM rewrite doesn't involve gas-cost equivalence with the EVM specification. Therefore, all gas-related hardcoded values or formulas extracted from the EVM should be removed from the codebase. For example, expanding the memory should not calculate the associated gas costs, given that the underlying model is completely different from traditional EVM's

**Describe the Feature Request**

**Describe Preferred Solution**

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [x] Yes
- [ ] No

**Comment by Eikix** [comment]
Important update: we are gathering some bugs in the [Kakarot v0 codebase](https://github.com/kkrt-labs/kakarot), we need to make sure each issue and each PR in Kakarot-ssj is aware of the lists of known bugs. Look at this link everytime you take an issue and check your issue isn't targeted by a known bug.

**Comment by Eikix** [comment]
Important update: we are gathering some bugs in the [Kakarot v0 codebase](https://github.com/kkrt-labs/kakarot), we need to make sure each issue and each PR in Kakarot-ssj is aware of the lists of known bugs. Look at [this tracking issue](https://github.com/kkrt-labs/kakarot-ssj/issues/324) everytime you take an issue and check your issue isn't targeted by a known bug. Will add this reminder in many places to make sure we keep track of known bugs.
