### ISSUE TITLE
dev: explore an accumulator based pattern to apply storage updates

### ISSUE THREAD

**Issue by enitrat** [kkrt-labs/kakarot-ssj#293]
> we could track modified storage addresses in a dict, and sload/sstore would read/write to this dict, and if the value is 0 write/read to storage instead. We would track all modified storage addresses in an array and then loop through when the current context exits.

> Might be more interesting gas-wise as if a subcontext reverts, we divide the read/write syscalls amount by two

Exploring this feature can be interesting as it is way less expansive to handle subcontext reverts. However, this might introduce overhead costs for OK cases

**Comment by Eikix** [comment]
Important update: we are gathering some bugs in the [Kakarot v0 codebase](https://github.com/kkrt-labs/kakarot), we need to make sure each issue and each PR in Kakarot-ssj is aware of the lists of known bugs. Look at this link everytime you take an issue and check your issue isn't targeted by a known bug.

**Comment by Eikix** [comment]
Important update: we are gathering some bugs in the [Kakarot v0 codebase](https://github.com/kkrt-labs/kakarot), we need to make sure each issue and each PR in Kakarot-ssj is aware of the lists of known bugs. Look at [this tracking issue](https://github.com/kkrt-labs/kakarot-ssj/issues/324) everytime you take an issue and check your issue isn't targeted by a known bug.
