### ISSUE TITLE
feat: add a `store_padded_segment ` method to memory

### ISSUE THREAD

**Issue by enitrat** [kkrt-labs/kakarot-ssj#335]
# Feature Request

**Describe the Feature Request**
Several opcodes have the following behavior: 
- Given an array of bytes, copy `size` bytes starting from the `offset` index into memory starting from `dest_offset` 
- If `size` is bigger than the slice to copy to memory, then fill the remaining memory elements with zeroes

It's not very efficient to duplicate this behavior. Instead, we can add a method to memory:

```rust
fn store_padded_segment(ref self: Memory, offset: usize, length:usize, source:Span<u8>);
```

This function will perform the following:

- It first checks that the length is not 0 and returns early if so.
- It resizes the memory if needed to fit the data being written.
- Copy all elements from source to the memory, starting at `offset`
- Copy `length - source.len()` zeroes afterwards

You will then refactor the `xcopy` opcodes to use this newly introduced method.
**Describe Preferred Solution**

You will add the required unit tests, covering correct execution of the function and different edge cases.
**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [ ] Yes
- [ ] No

**Comment by khaeljy** [comment]
Can I do it?

**Comment by khaeljy** [comment]
If I've understood correctly, parameter `offset` designates the start offset in the `source` Span. So I think we're missing a `dest_offset` parameter to define the start offset in memory.

@enitrat Is that right?

**Comment by khaeljy** [comment]
Or does `offset` designate the memory start offset, and we have no offset for the source start (offset = 0)?

**Comment by enitrat** [comment]
Yep second one

**Comment by enitrat** [comment]
@khaeljy I will get back to this tmr, indeed I think there's a confusion but
- source is the slice of the data to copy to memory (not padded, not modified)
- offset is the memory address we start the copy at
- length is the amount of data we will copy

**Comment by khaeljy** [comment]
Thanks, that's clearer. Indeed, this sentence confused me a bit: `Given an array of bytes, copy size bytes starting from the offset index into memory starting from dest_offset`
