### ISSUE TITLE
feat: Create a `i256` type with its associated methods

### ISSUE THREAD

**Issue by enitrat** [kkrt-labs/kakarot-ssj#336]
# Feature Request

**Describe the Feature Request**
Several opcodes perform signed integer operations (SLT, SGT, SDIV, etc.). To prevent confusion and leverage Cairo's typesystem we should refactor our codebase and create a type `i256` that will be used to perform these operations. 

**Describe Preferred Solution**
- [ ] Inside the `utils` crate, you will create a `i256.cairo` file, inside which you will define the `i256` struct. This struct is just a wrapper around a `u256`. 
- [ ] You will remove the `SignedPartialOrd` trait, and instead implement the `PartialOrd` trait for `i256` and refactor the related opcodes to use `i256` and the comparison operators
- [ ] You will implement `Bitshift` for `i256` and refactor the `SAR` opcode to use it
- [ ] You will implement the `Div` and `Rem` traits for `i256` using `u256_signed_div_rem` and refactor the `SDIV` and `SMOD` opcodes
- [ ] You will create a `pop_i256` method in the stack that pops an item off the stack and wraps it as a `i256`
**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [ ] Yes
- [ ] No

**Comment by khaeljy** [comment]
Can I do it?

**Comment by danilowhk** [comment]
Assigned!
