### ISSUE TITLE
feat: add `pop_type` methods to `Stack`

### ISSUE THREAD

**Issue by enitrat** [kkrt-labs/kakarot-ssj#337]
# Feature Request

**Describe the Feature Request**

Several opcodes have the following behavior:
- Pop the last element off the stack (by default a u256)
- Converts it to the required input type of an EVM function
- Use that value with the new converted type

Instead of duplicating this behavior in several opcodes, we can have several methods `pop_type` on the Stack that perform this conversion tentative in a single place.

**Describe Preferred Solution**
- [ ] Implement `pop_usize`
- [ ] Implement `pop_eth_address`
- [ ] Refactor all functions that converted a popped u256 value to a usize and use `pop_usize` instead. If multiple values were popped together with `pop_n`, simply use multiple `pop_usize` instead.

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [ ] Yes
- [ ] No

**Comment by lambda-0x** [comment]
i can take this up

**Comment by lambda-0x** [comment]
should it be `pop_usize` or an explicit `pop_u32`. i'd prefer later.
