### ISSUE TITLE
feat: Divide `Bitshift` into `Bitshift` and `WrappingBitshift`

### ISSUE THREAD

**Issue by enitrat** [kkrt-labs/kakarot-ssj#338]
# Feature Request

**Describe the Feature Request**
Bitshift currently combines implementations of "panickable" operations and "wrapping" operations. We want to split these in different traits to make the codebase more modular.
**Describe Preferred Solution**
- [ ] Split Bitshift into two traits
- [ ] Modified the existing implementations of bitshift
- [ ] Removed the `shl` and `shr` implementations for `felt252`
- [ ] Add support for `wrapping_shr` for the `felt252` type by converting the value to `u256`, doing the operations, and then back to `felt252` instead of panicking

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [ ] Yes
- [ ] No

**Comment by trbutler4** [comment]
Dibs!

**Comment by danilowhk** [comment]
Assigned!
