### ISSUE TITLE
dev: refactor constants to be base 2 instead of base 256

### ISSUE THREAD

**Issue by lambda-0x** [kkrt-labs/kakarot-ssj#358]
see: https://github.com/kkrt-labs/kakarot-ssj/pull/329#discussion_r1328656094

This constants needs to be updated to base 2 equivalent, uses of this variables should also be updated.

https://github.com/kkrt-labs/kakarot-ssj/blob/83c2ff4c296d9b2386a5bb595ebb78ac7198ad38/crates/utils/src/constants.cairo#L31-L46

**Comment by enitrat** [comment]
I don't understand, what's "base-2 equivalent"? like POW_256_2_U128 should be POW_2_16 instead?

**Comment by lambda-0x** [comment]
> I don't understand, what's "base-2 equivalent"? like POW_256_2_U128 should be POW_2_16 instead?

yes
