### ISSUE TITLE
investigation: explore how to reproduce flows from Kakarot Cairo Zero with regards to testing and injecting JSON formatted tests into cairo1

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-ssj#36]
# Feature Request

**Describe the Feature Request**

In v0 Kakarot, we could run tests using pytest, we could load Json files and run tests with cases/ parameters: [link](https://github.com/kkrt-labs/kakarot/blob/40fc24ab352a0a5a73863410358097c037312f67/tests/integration/bytecodes.py#L11)

In v1 Kakarot, we want to be able to run ethereum/tests directly against our codebase. 
For more information, we need to know about: https://github.com/kkrt-labs/kakarot/issues/660

**Comment by ftupas** [comment]
Kindly assign, thank you

**Comment by ftupas** [comment]
Found this issue here https://github.com/foundry-rs/starknet-foundry/issues/242, they're planning to add it as it's part of the foundry [file cheatcode](https://book.getfoundry.sh/cheatcodes/fs)
