### ISSUE TITLE
feat: create the upgradeadable component for kakarot

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-ssj#421]
## Feature Request

Make Kakarot upgreadable

### Describe the Feature Request

1. in core contracts, create the logic for upgradability as a component, draw inspiration from ownable
2. in kakarot core, import the logic of upgrading, and make sure the upgrade can only be performed by an owner
3. test the component unitarily 
4. test kakarot core

### Additional Context

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [ ] Yes
- [ ] No

**Comment by Eikix** [comment]
@bajpai244 you can take this if you'd like

**Comment by bajpai244** [comment]
@Eikix I would love to take it :)
