### ISSUE TITLE
dev: optimize `pack_bytes` by skipping checks for initial `n` chunks with more than 31 bytes

### ISSUE THREAD

**Issue by enitrat** [kkrt-labs/kakarot-ssj#426]
https://github.com/kkrt-labs/kakarot-ssj/pull/425/files#diff-8ab8f65f6e1ee9e453913c37b065a35340c0de8ac765d0649c53f5dc83d200d5R526-R539

Refactor the `pack_bytes` function and optimize deserialization of Span<u8> to ByteArray. Instead of calling `append_byte` byte by byte, we can simply pack the full 31-bytes chunks ourselves and append them directly to the `data` field. 
For the last incomplete chunk, we know that it's length is `len() % 31`. we can pack these together and modify the `pending_word` and `pending_word_len` fields directly.

**Comment by chachaleo** [comment]
Can I take it ?

**Comment by enitrat** [comment]
it's now under BytesArrayExTrait - `from_bytes`
