### ISSUE TITLE
feat: create a ExecutionContext struct that is adapted to the migration path

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-ssj#43]
# Feature Request

**Describe the Feature Request**

We need to describe the new ExecutionContext in kakarot-ssj

Kakarot Cairo 0:
```
  struct ExecutionContext {
        call_context: CallContext*,
        program_counter: felt,
        stopped: felt,
        return_data: felt*,
        return_data_len: felt,
        stack: Stack*,
        memory: Memory*,
        gas_used: felt,
        gas_limit: felt,
        gas_price: felt,
        starknet_contract_address: felt,
        evm_contract_address: felt,
        calling_context: ExecutionContext*,
        sub_context: ExecutionContext*,
        destroy_contracts_len: felt,
        destroy_contracts: felt*,
        events_len: felt,
        events: Event*,
        create_addresses_len: felt,
        create_addresses: felt*,
        revert_contract_state: RevertContractState*,
        reverted: felt,
        read_only: felt,
    }
```

**Describe Preferred Solution**

We could split the ExecutionContext well in themes:
dynamic, static data

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [ ] Yes
- [ ] No

**Comment by jobez** [comment]
> is this an issue for "creating the execution context" in cairo1 or to design a new execution context possibly optimized?

optimized where where separate aspects of the context that are updated versus those that are static. in evm terms, this would be dimensions that are environment data (set once upon initialization of execution context and never changed) and dynamic fields that are changed in the flow of execution.

**Comment by enitrat** [comment]
I am currently exploring how it would be like to have, as you said , a "dynamic" part and a "static" part in the ExecutionContext struct. And use pointers to structs instead of structs, where it makes sense.

Basically something like

```rust

#[derive(Copy, Drop)]
struct StaticExecutionContext {
    call_context: @CallContext,
    gas_limit: u64,
    gas_price: u64,
    starknet_contract_address: ContractAddress,
}

#[derive(Destruct)]
struct ExecutionContextSplit {
    static_context: Box<StaticExecutionContext>,
    gas_used: u64,
    program_counter: u32,
    stopped: bool,
    return_data: Array<felt252>,
    stack: Stack
}
```

and 
```rust
/// Stores all data relevant to the current execution context.
#[derive(Destruct)]
struct ExecutionContextAllInOne {
    /// The call context data.
    call_context: @CallContext,
    /// Keeps track of the current position in the program as it is being executed.
    program_counter: u32,
    /// States if the current execution is halted.
    stopped: bool,
    /// The region used to return a value after a call.
    return_data: Array<felt252>,
    /// The gas used.
    gas_used: u64,
    /// The gas limit.
    gas_limit: u64,
    /// The gas price.
    gas_price: u64,
    /// The starknet address of the contract interacted with.
    starknet_contract_address: ContractAddress,
    /// The stack.
    stack: Stack,
}
```

From what I've seen, just with this small experiment, the "split" implementation costs way less gas on a simple operation like updating the gas_used field. (~15%) Probably because under the hood, updating the struct which has a single pointer to the static ctx instead of multiple fields costs way less

**Comment by danilowhk** [comment]
Looking into it, having the execution context split, feels like will bring perfomance and as the split is not so big, the code readability is still fine?

Another idea would be split even memory, stack and the u32/ u64 values(this could be all stored on one Dict that gets updated every step)?

**Comment by danilowhk** [comment]
From the tests performances, here is my proposal:

## Current

```cairo
/// The execution context.
/// Stores all data relevant to the current execution context.
#[derive(Destruct)]
struct ExecutionContext {
    call_context: CallContext,
    program_counter: u32,
    stack: Stack,
    stopped: bool,
    return_data: Array<u8>,
    memory: Memory,
    gas_used: u64,
    gas_limit: u64,
    gas_price: u64,
    starknet_address: ContractAddress,
    evm_address: EthAddress,
    // TODO: refactor using smart pointers
    // once compiler supports it
    //calling_context: Nullable<ExecutionContext>,
    //sub_context: Nullable<ExecutionContext>,
    destroy_contracts: Array<EthAddress>,
    events: Array<Event>,
    create_addresses: Array<EthAddress>,
    revert_contract_state: Felt252Dict<felt252>,
    reverted: bool,
    read_only: bool,
}```

## New
### Groups:

- StaticData
- DynamicData
- Stack
- Memory
- program counter(this changes a lot more than dynamic data)


```cairo
#[derive(Destruct)]
struct StaticExecutionContext {
    call_context: CallContext,
    starknet_address: ContractAddress,
    evm_address: EthAddress,
    origin: EthAddress,
    read_only: bool,
}

#[derive(Destruct)]
struct DynamicExecutionContext {
    stopped: bool,
    return_data: Array<u8>,
    destroy_contracts: Array<EthAddress>,
    events: Array<Event>,
    create_addresses: Array<EthAddress>,
    revert_contract_state: Felt252Dict<felt252>,
    reverted: bool,
}

stack = Stack::new()
memory = Memory::new()
program_counter: u32 = 0 (initial)

```

**Comment by Eikix** [comment]
How about subcalls? Just a question, haven't thought about it yer

**Comment by enitrat** [comment]
@danilowhk A few questions/suggestions:

- I think we should group `DynamicExecutionContext` and `StaticExecutionContext` together in a `ExecutionContext`struct that takes pointers to these structs
- Don't forget that increasing the number of function parameters also has an impact on gas - if we now pass each opcode 5 parameters vs. 1 previously, it might not be as beneficial as we think
- Is isolating stack / memory / program_counter really beneficial when it comes to gas savings, especially if they're packed in `ExecutionContext` along `DynamicExecutionContext` and `StaticExecutionContext` ?
- Don't forget that complexity bad and we don't want to have the complexity demon enter our codebase

**Comment by Eikix** [comment]
I suspect this issue is also done, except if we consider #177

**Comment by enitrat** [comment]
indeed
