### ISSUE TITLE
feat: create RLP::encode method

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-ssj#440]
## Feature Request

For computing the eth address of a contract, we need to compute the RLP::encode(deployer_address, deployer_nonce) and then hash it, and take the 20 least significant bytes.

### Describe the Feature Request

Implement RLP::encode

### Related Code

The RLP library made by @Quentash 

### Additional Context

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [ ] Yes
- [ ] No

**Comment by Noeljarillo** [comment]
Can I get this one?
