### ISSUE TITLE
feat: Create a layer of abstraction around transient storage

### ISSUE THREAD

**Issue by enitrat** [kkrt-labs/kakarot-ssj#442]
# Local State

A challenge with the implementation of Kakarot is that since it lives as a
contract deployed on chain, it cannot manipulate the underlying state of the
blockchain once it has performed modifications on it to revert the changes made.

This means that before committing any changes to the blockchain, Kakarot must
ensure that the changes are valid. This is done by maintaining a local state
that is updated as the code is executed.

The machine is created along with a default empty state. The state is a struct
that wraps dictionaries holding the values stored in the blockchain storage
modified locally.

Because of technical limitations around the usage of dictionaries, instead of
having one state per execution context that we could merge into the parent state
if the context exits successfully or discard if the context reverts, we have one
global `State` structs that achieves the same behavior by tracking transactional
changes, which refers to the changes made inside the current transaction as a
whole, and a contextual changes, which refers to changes made inside the current
execution context.

The local state is updated as the code is executed, and when an execution
context is finished, we merge the contextual state updates into the transactional state.
When a transaction finishes, we apply the transactional state diffs by writing them
inside the blockchain storage.

This design allows us to simulate reverting the changes made to the blockchain
storage by simply discarding the contextual state updates, and to commit the changes
by applying the transactional state updates.

## Implementation

We need to be able to store in the local state the current information:

- The existing modified accounts content, including balance, nonce, code and
  storage updates,
- The emitted events,
- The newly created accounts,
- The deleted accounts through `selfdestruct`
- The pending transfers of native tokens.

At the end of an execution context, we can merge the contextual state into the transactional
state, and at the end of a transaction, we can apply the transactional state updates to
the blockchain storage, emit pending events, and perform actual token transfers.

## Implementation design

The ideal implementation would be fairly simple: A single `StateChangeLog` field
holding the account updates, and an `Array` field holding the emitted events.

However, we decided to implement it as follows:

```rust
struct State {
    /// Accounts states - without storage and balances, which are handled separately.
    accounts: StateChangeLog<Account>,
    /// Account storage states. `EthAddress` indicates the target contract,
    /// `u256` indicates the storage key.
    /// We have to store the target contract, as we can't derive it from the
    /// hashed address only when finalizing.
    accounts_storage: StateChangeLog<(EthAddress, u256)>,
    /// Account states
    /// Pending emitted events
    events: EventLog,
    /// Account balances updates. This is only internal accounting and stored
    /// balances are updated when commiting transfers.
    balances: StateChangeLog<u256>,
    /// Pending transfers
    transfers: StateChangeLog<Transfer>,
}
```

A `StateChangeLog` is a data structure that tracks the changes made to a
specific object both at the context-level and at the transaction-level using the
mechanism specified above. The `EventLog` is a simplified version of this
concept that only tracks the events emitted.

```rust
/// The StateChangeLog tracks the changes applied to storage during the execution of a transaction.
/// Contextual changes tracks the changes applied inside a single execution context.
/// Transactional changes tracks the changes applied in the entire transaction.
/// Upon exiting an execution context, contextual changes must be finalized into transactional changes.
/// Upon exiting the transaction, transactional changes must be finalized into storage updates.
struct StateChangeLog<T> {
    contextual_changes: Felt252Dict<Nullable<T>>,
    contextual_keyset: Array<felt252>,
    transactional_changes: Felt252Dict<Nullable<T>>,
    transactional_keyset: Array<felt252>
}
```

```rust

/// The EventLog tracks the events emitted during the execution of a transaction.
#[derive(Drop)]
struct EventLog{
    contextual_events: Array<Event>,
    transactional_events: Array<Event>,
}
```

The reason for this implementations are that:

- Including `balances` inside the `Account` struct would require loading the
  entire bytecode of a ContractAccount, even for simple transfers - which is not
  optimized as it can be an expensive operation. Therefore, by storing these
  changes in a standalone field in the state, we can apply balance changes
  without loading the accounts first.
- Storage changes are modeled using a dictionary where the key is the storage
  address to update, and the value is the updated value. However, we can't
  create nested dictionaries in Cairo - so we have to separate the accounts
  storage updates from the account updates themselves.
- However, this last point can be abstracted from the user by ensuring that
  account storage updates can only be performed by providing the related Account
  as a parameter. This way, we can derive the storage address from the account
  address and the storage key.

**Comment by ClementWalter** [comment]
> The ideal implementation would be fairly simple: A single StateChangeLog field holding the account updates, and an Array field holding the emitted events.

> However, we decided to implement it as follows:

why wouldn't we do the "ideal" implementation then?

**Comment by ClementWalter** [comment]
Regarding the diff with KKT0 (see https://github.com/kkrt-labs/kakarot/blob/main/src/kakarot/model.cairo)

we have: 
- state has the  `accounts_storage` in a separate field, while it's in the `account` in KKT0. In KKT0, I started doing the same but eventually found that it was more natural and easy to have the storage inside the account it belongs to. I understand the cairo 1 limitation rn for this design decision
- need to maintain a list of keys because it's not possible to iterate over the keys of a dict (ie something like  `dict.keys()`)
- because we have one single `State`, each field has two dicts instead of one

I don't see the definition of the `Account` struct, this as well came after few iterations and especially the addition of the `selfdestruct` field

```
    struct Account {
        address: felt,
        code_len: felt,
        code: felt*,
        storage_start: DictAccess*,
        storage: DictAccess*,
        nonce: felt,
        selfdestruct: felt,
    }
```

simplified a lot the management of SELFDESTRUCT

**Comment by enitrat** [comment]
> why wouldn't we do the "ideal" implementation then?

Because of restrictions from Cairo1 preventing us from having nested dicts, we have to bring sub-dicts to the top level of the state data structure. Also for optimization purposes we also extracted the balance field (as you did in KKT0)

> I don't see the definition of the Account struct, this as well came after few iterations and especially the addition of the selfdestruct field

Inspired by yours, except that the storage field was extracted

```rust
struct Account {
    account_type: AccountType,
    code: Span<u8>,
    nonce: u64,
    selfdestruct: bool,
}

enum AccountType {
    EOA: EOA,
    ContractAccount: ContractAccount,
}
// Where both EOA and ContractAccount are structs containing evm_address and starknet_address
```
> need to maintain a list of keys because it's not possible to iterate over the keys of a dict (ie something like dict.keys())

Eventually this will become possible in Cairo once we can iterate over squashed dict keys - I saw Ori mention this quite a few times.

**Comment by ClementWalter** [comment]
interesting I didn't add the `AccountType`. Actually I'm more and more suspicious about this distinction we made in the code. I feel like from the EVM point of view, addresses/account are either "free" or not, but not EOA or CA per se. The collision check is `has_nonce_or_code`, and that's it.

Maybe we should just keep one single account contract, implementing the Starknet Account interface + having extra fields (like bytecode, though these extra fields could also be stored in Kakarot main contract)

**Comment by enitrat** [comment]
> I feel like from the EVM point of view, addresses/account are either "free" or not, but not EOA or CA per see

While this is true, the way we handle accounts in Kakarot requires making this distinction - which is why I believe that our account model should reflect this. By using the type system and correctly instantiating account objects with the correct account type, we can actually "abstract/simplify/improve" our codebase and reduce bugs
