### ISSUE TITLE
bug: bytecode not ending with STOP or RETURN will revert

### ISSUE THREAD

**Issue by greged93** [kkrt-labs/kakarot-ssj#446]
## Bug Report

**Kakarot version:** [7b6d03b](https://github.com/kkrt-labs/kakarot-ssj/commit/7b6d03bb6f84ccbe02f62573464491cda884cc33)

**Current behavior:**
If return bytecode of a contract that doesn't end with RETURN or STOP, the EVMInterpreter will set the current state of the execution to reverted.

**Expected behavior:**
If $pc > \lVert bytecode \rVert$, the next executed opcode should be STOP (see [comment](https://github.com/kkrt-labs/kakarot-ssj/pull/441#discussion_r1366623144) on PR for `CALL` opcode).

**Steps to reproduce:**

- `anvil`
- `cast rpc anvil_setCode 0x00000000000000000000000000000000deadbeef 0x6042600055` sets the bytecode to PUSH1 42 PUSH1 0 SSTORE, meaning there is no return and no stop.
- `cast send 0x00000000000000000000000000000000deadbeef --value 1 --private-key any_private_key_from_anvil`
- Should return status `1`
- You can also check that the tx ran with `cast run tx_hash`
- If you check `cast rpc eth_getStorageAt 0x00000000000000000000000000000000deadbeef 0x0 latest`, you should see that the storage at `0x0` is `0x0000000000000000000000000000000000000000000000000000000000000042`.

**Related code:**
https://github.com/kkrt-labs/kakarot-ssj/blob/7b6d03bb6f84ccbe02f62573464491cda884cc33/crates/evm/src/interpreter.cairo#L73-L76

**Comment by Eikix** [comment]
I can take this
