### ISSUE TITLE
feat: Create an Account enum and associated traits

### ISSUE THREAD

**Issue by enitrat** [kkrt-labs/kakarot-ssj#448]
### Describe the Feature Request
Modeling accounts and associated methods properly allows us to avoid duplicating code to check whether an account is an EOA or a CA. 
### Describe Preferred Solution
- Create an `Account` enum, with `EOA` and `ContractAccount` variants. 
- Create associated methods that return the variant corresponding to an account at address `evm_address`
- TODO: determine other useful methods to add.
### Additional Context

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [ ] Yes
- [ ] No

**Comment by Eikix** [comment]
I can take this today or tomorrow 🔭🏎️

**Comment by enitrat** [comment]
I'm almost done @Eikix
