### ISSUE TITLE
dev: add a pre-push/pre-commit hook that runs scarb fmt to avoid useless failed CIs

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-ssj#463]
I noticed we have many CIs failing due to scarb fmt --check, 
Although it's quite fast to fix, we're wasting CI time as well as speed to merge.

**Comment by Eikix** [comment]
Ah well it seems this has already been done. Let me check if it works properly and close this issue if so

**Comment by enitrat** [comment]
The culprit is the Trunk tool that overrides the local `.git/config:hooksPath` value to use trunk hooks instead of your repo's local hooks.

**Comment by enitrat** [comment]
@Eikix now possible?

**Comment by Eikix** [comment]
> @Eikix now possible?

normally yes,
i will ask clement to see how to setup scarb with trunk

**Comment by enitrat** [comment]
scarb in trunk now.
