### ISSUE TITLE
Design a new flow to pre-compute a SN address for a CA or an EOA

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-ssj#482]
Thanks to #481 we will now deploy a unique SN account both for EOAs and CAs

Problem:
- We need a deterministic way to get a SN address starting from an EVM address. 
- Up until now, we were using the EOA class hash to deterministically compute the resulting SN address for a specific evm address. Now that we also have CAs as SN SCs, we need a general way to derive a correct SN address.
- In KKT0, we use the proxy pattern to ensure there is only one class hash for both EOA and CAs, that way we're certain not to have two SN addresses for the same EVM address. But cairo 1 does not rely on the proxy pattern.

Proposal:
- Create a chrysallis account (can change name):
```rust
/// Pseudo code
mod Account {
   Storage {
       kakarot_address: ContractAddress,
       evm_address: EthAddress,
       is_initialized: bool,
   }

// if we need to upgrade this chrysallis or staged contract
fn initialize(class_hash: ClassHash) {
    assert(is_initialized.read() == false, 'already initialized');
    assert_caller_is_kakarot();
    is_initialized.write(true);
    replace_class(class_hash);
}
```

**Comment by enitrat** [comment]
Sounds good, deployment flow of an Account (whatever its type) will be a sequential deployment of the "chrysalis" to get a deterministic address, and then upgrade it to the relevant implementation.

>        is_initialized: bool,

I'm not sure if this is required, given that I do not see any scenario where the deploy + upgrade is not performed sequentially in the same transaction. The `initialize` entrypoint will not be a part of the upgraded contract class ABI, so no need to check for this imo

<img src="https://github.com/kkrt-labs/kakarot-ssj/assets/60658558/5e842f0e-22b0-4941-8080-3aba373b961f" width="200">
