### ISSUE TITLE
bug: ensure a context is not static (self.read_only()) for opcodes that write to storage

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-ssj#484]
## Bug Report

**Current behavior:**

currently, when entering some opcodes that change the storage, we don't check that self.read_only == false

**Expected behavior:**

Such as in the specs: https://github.com/ethereum/execution-specs/blob/3fe6514f2d9d234e760d11af883a47c1263eff51/src/ethereum/istanbul/vm/instructions/system.py#L344
We need to ensure the context is not read only for:
- SStore
- Create
- Create2
- Call opcodes if value > 0 AND !self.is_read_only
- Logs opcodes (https://github.com/ethereum/execution-specs/blob/3fe6514f2d9d234e760d11af883a47c1263eff51/src/ethereum/paris/vm/instructions/log.py#L71)

In these cases, the current_ctx should revert

**Comment by enitrat** [comment]
@Eikix Should it revert or should the state transition just be discarded? I remember @ClementWalter mentioning that in KKT0, calls and invoke are the same but invoke commits state updates.

**Comment by Eikix** [comment]
> @Eikix Should it revert or should the state transition just be discarded? I remember @ClementWalter mentioning that in KKT0, calls and invoke are the same but invoke commits state updates.

We'll have to check in each case and make sure we understand the interactions.
Afaik, the call should revert if unauthorised state diff are done
