### ISSUE TITLE
dev: adopt the new #[abi_embed(v0)] notation on the whole repo

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-ssj#488]
As a result of this release: https://community.starknet.io/t/cairo-v2-3-0-release-candidate/101137

We will now follow the new norm

```[tasklist]
### Tasks
- [ ] In contracts crate, adopt the new abi_per_item norm
- [ ] Mark with external only the required functions
```

**Comment by Eikix** [comment]
ERRATUM: I want the abi_embed for when we implement an Interface, otherwise abi_per_item

**Comment by Eikix** [comment]
Can check existing PRs / code for those keywords

**Comment by akhercha** [comment]
Hey, happy to try this one!

**Comment by Eikix** [comment]
Awesome;D
