### ISSUE TITLE
feat: replace all occurences of Dispatchers with SafeDispatchers

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-ssj#494]
## Feature Request

We want to be able to handle syscall failures when they become handlable,
This will happen soon.

In the meantime, we want to EVM layer, when calling contracts with Dispatchers, to be able to match on the Result.
We must therefore use SafeDispatchers

```[tasklist]
### Tasks
- [ ] Go through the codebase, and find occurrences of contract calls using a Dispatcher. Replace it with SafeDispatcher
- [ ] Handle the error, with SyscallError variant of EVMError
- [ ] Check tests
``` 

### Additional Context

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [ ] Yes
- [ ] No

**Comment by TAdev0** [comment]
@Eikix  may i try to work on this one?

**Comment by TAdev0** [comment]
@enitrat  thank you for your response!
