### ISSUE TITLE
dev: refactor test contracts deployment

### ISSUE THREAD

**Issue by enitrat** [kkrt-labs/kakarot-ssj#509]
- When we deploy any kind of account, we need deploy a `native_token` and the `kakarot_core` contract because the generic Account's `initialize` function reads from KakarotCore storage to approve spending of the native token.
- When we interact in any way with the Kakarot State, we need to `set_contract_address` the test runner to the kakarot contract.

This pattern is often used when testing some features that require access to the Starknet state:
```rust
    let native_token = deploy_native_token();
    let kakarot_core = deploy_kakarot_core(native_token.contract_address);
    testing::set_contract_address(kakarot_core.contract_address);
```

You will implement a test utils that performs these 3 operations in a single function. This util will then be called as

```rust
let (native_token, kakarot_core) = setup_contracts_for_testing()
```

**Comment by akhercha** [comment]
Hey, happy to do this one!
