### ISSUE TITLE
feat: generic `from_bytes` implementation

### ISSUE THREAD

**Issue by bajpai244** [kkrt-labs/kakarot-ssj#512]
### Describe the Feature Request

As of now we have an implementation providing a helper [from_bytes](https://github.com/kkrt-labs/kakarot-ssj/blob/efc83c577b20ed38d94f2dd99d4f1a8fad023ade/crates/utils/src/helpers.cairo#L532C3-L532C3) which allows creation of a u32 from bytes.

We need a generic implementation that can allow creating other unsigned integer types as well from byte array.

**Comment by enitrat** [comment]
Blocked until a future release of the corelib with `num::traits::bits_size`

**Comment by TAdev0** [comment]
@enitrat  this trait is now available in corelib. May I work on it ?

**Comment by aniketpr01** [comment]
@enitrat can i take this?

**Comment by enitrat** [comment]
Hi, this is paused for now
