### ISSUE TITLE
feat: stop deploying all undeployed accounts in state commit_accounts

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-ssj#519]
### Describe the Feature Request

- check if the account exists before deploying (already in place)
- check if the account SHOULD be deployed, i.e. has been scheduled for deployment, or is simply "touched" (e.g. only transfer value). this can be done with the hasNonceOrCode check -> nonce != 0 OR code is not empty

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [ ] Yes
- [ ] No

**Comment by enitrat** [comment]
Closed by #526
