### ISSUE TITLE
feat: implement `validate_tx` method for ethereum transactions.

### ISSUE THREAD

**Issue by bajpai244** [kkrt-labs/kakarot-ssj#523]
## Feature Request

Implement the [`validate_tx`](https://github.com/kkrt-labs/kakarot-ssj/blob/d8cbf9c9467a1ef7512d1c157fa0cb2cec8a3059/crates/utils/src/eth_transaction.cairo#L152) method for Ethereum transactions.

**Comment by Eikix** [comment]
Note that the new validate flow is := RPC will send to the EOA for validation (for tx type legacy, 1 and 2):
- The RLP encoded transaction payload (without r, s, v),
- The signature inside the get_tx_info.unbox.signature field

This is slightly different from Kakarot 0 where the full payload+signature was sent, and the EOA had to decode, and reencode. 
This is documented 

The job of the `validate` function will be to:
- hash the RLP encoded transaction payload
- verify the eth signature
- decode the RLP encoded transaction, and check chain_id and relevant fields
- return VALIDATE if successful
