### ISSUE TITLE
dev: unit test `init_call_sub_ctx` and `prepare_call`

### ISSUE THREAD

**Issue by enitrat** [kkrt-labs/kakarot-ssj#542]
Write unit tests for these two functions

https://github.com/kkrt-labs/kakarot-ssj/blob/main/crates/evm/src/call_helpers.cairo#L45-L47

https://github.com/kkrt-labs/kakarot-ssj/blob/main/crates/evm/src/call_helpers.cairo#L79-81

**Comment by bajpai244** [comment]
@enitrat I can take this.
