### ISSUE TITLE
dev: use a builder pattern to construct the machine object in tests

### ISSUE THREAD

**Issue by enitrat** [kkrt-labs/kakarot-ssj#546]
https://github.com/kkrt-labs/kakarot-ssj/blob/239fb4c069b90964adb920e95dc92fe7a331b0c7/crates/evm/src/tests/test_utils.cairo#L264-L265

https://github.com/kkrt-labs/kakarot-ssj/blob/239fb4c069b90964adb920e95dc92fe7a331b0c7/crates/evm/src/tests/test_utils.cairo#L264-L265

https://github.com/kkrt-labs/kakarot-ssj/blob/239fb4c069b90964adb920e95dc92fe7a331b0c7/crates/evm/src/tests/test_utils.cairo#L276-L277

https://github.com/kkrt-labs/kakarot-ssj/blob/239fb4c069b90964adb920e95dc92fe7a331b0c7/crates/evm/src/tests/test_utils.cairo#L300-L301

https://github.com/kkrt-labs/kakarot-ssj/blob/239fb4c069b90964adb920e95dc92fe7a331b0c7/crates/evm/src/tests/test_utils.cairo#L312-L313

https://github.com/kkrt-labs/kakarot-ssj/blob/239fb4c069b90964adb920e95dc92fe7a331b0c7/crates/evm/src/tests/test_utils.cairo#L322-L323

Refactor all these test utils. You will use the builder pattern to create a MachineBuilder object with all fields set to 0, and use setters to instanciate the machine with the fields necessary.

**Comment by edisontim** [comment]
Hey, will this be solved by #541 or can I take this one :) ?

**Comment by enitrat** [comment]
You can take it!

**Comment by enitrat** [comment]
@Eikix do we need this in source as well? I'd say this could be a test struct/impl only

**Comment by Eikix** [comment]
> @Eikix do we need this in source as well? I'd say this could be a test struct/impl only

agreed!

**Comment by edisontim** [comment]
> setup_machine_with_target

This one is from a fork?

**Comment by edisontim** [comment]
Shouldn't ```setup_machine_with_bytecode``` also be included in there?

**Comment by enitrat** [comment]
yep!
