### ISSUE TITLE
dev: Explore how we architect "Contract Account" to store bytecode as 32 or 16 bytes instead of 1-byte / storage

### ISSUE THREAD

**Issue by danilowhk** [kkrt-labs/kakarot-ssj#55]
**Describe the Feature Request**

On Cairo 0, we are currently storing all bytecodes as 1-byte data. So for a 10Kb contract, we are triggering 10.000 stores(when deploying the contract) and also 10.000 reads(on any contract call), which is expensive as for every storage or read a hash is calculated.

With storage improvement to 32 or 16 bytes, we decrease the amount of store and reads. 

**Describe Preferred/Possible Solution**

1. Use storage index: Besides storing 32/16 bytes for each storage, once the hash for the storage location is calculated we can access up to 256 more slots by adding to the index.

2. Use dw(currently not possible). We could use dw to store the code in the contract and just access them as needed.

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [x] Yes
- [ ] No

**Comment by Eikix** [comment]
Closing as PR and design will encompass it #279 
Also this issue isn't accurate, as we already pack 16 bytes into storage for bytecode
