### ISSUE TITLE
dev: make eth_transactions utils accept Span<felt252> in place of Span<u8> 

### ISSUE THREAD

**Issue by bajpai244** [kkrt-labs/kakarot-ssj#561]
As of now, we use `Span<U8>` as the data type for encoded transactions, but this data, will come to us a `Span<felt252>`, as we get this data from the calldata.

We should directly process on top of `Span<felt252>` otherwise, we would have to do a conversion, which will consume more steps { steps are more critical in gas of `__validate__` of EOA  }

**Comment by bajpai244** [comment]
I realized that this change will also require changes in the RLP trait, hence this looks like a big change.

For now, I am converting `Span<felt252>` to `Span<u8>`, once this issue has been resolved then we can remove the conversion in __validate__ & __execute__, and use the calldata as it is.

**Comment by enitrat** [comment]
@bajpai244 still required after our discussion?

**Comment by bajpai244** [comment]
@enitrat , no, we don't need I guess.
