### ISSUE TITLE
feat: early return in add_transfer if recipient == sender or amount == 0 

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-ssj#572]
### Describe the Feature Request

inside `add_transfer`, early return if (it is NOT an error):
- recipient == sender
- amount == 0

**Comment by Mohiiit** [comment]
I would like to work on this one.

**Comment by Mohiiit** [comment]
Hey, I was trying setting the project up in the local, I am getting these errors:

`error: Method `array` not found on type "alexandria_storage::list::List::<core::bytes_31::bytes31>". Did you import the correct trait and impl?
 --> /kakarot-ssj/crates/contracts/src/contract_account.cairo:126:35
                data: stored_list.array().expect('failed to fetch bytecode'),
                                  ^***^

error: Ambiguous method call. More than one applicable trait function with a suitable self type was found: ResultTrait::expect and OptionTrait::expect. Consider adding type annotations or explicitly refer to the impl function.
 --> /cairo-projects/kakarot-ssj/crates/contracts/src/contract_account.cairo:126:43
                data: stored_list.array().expect('failed to fetch bytecode'),`

**Comment by enitrat** [comment]
Did you follow the installation steps in the readme? These one specifically.

## Installation
- Install [Scarb](https://docs.swmansion.com/scarb). To make sure your version always matches the one used by Kakarot, you can install Scarb [via asdf](https://docs.swmansion.com/scarb/download#install-via-asdf).

- [Fork](https://docs.github.com/en/get-started/quickstart/fork-a-repo) the repository and clone your fork (git clone https://github.com/<YOUR_USERNAME>/kakarot-ssj)

- Run make install to install the git hooks.

I think you're just facing a version mismatch or are not using the last `main` branch

**Comment by Mohiiit** [comment]
Yes.

1. Here is my scarb version:

scarb 2.3.1 (0c8def3aa 2023-10-31)
cairo: 2.3.1 (https://crates.io/crates/cairo-lang-compiler/2.3.1)
sierra: 1.3.0


2. Yes, I forked the branch and I am on main branch.
3. Here is the output of the make install:

bash scripts/install_hook.sh
pre-commit hook has been installed successfully!
pre-push hook has been installed successfully!

**Comment by enitrat** [comment]
> To make sure your version always matches the one used by Kakarot, you can install Scarb [via asdf](https://docs.swmansion.com/scarb/download#install-via-asdf).

This is why, you're not using the correct scarb version. You need this one

```shell
scarb 2.3.1+nightly-2023-11-22 (9d0de0a38 2023-11-22)
cairo: 2.3.1 (13f4c6aa2)
sierra: 1.3.0
```

installing via ASDF would handle the scarb version for you automatically

**Comment by Mohiiit** [comment]
Just for clarification here, transfer shouldn't be appended to the log in both of these cases right? or it should?

**Comment by enitrat** [comment]
no, it shouldn't
