### ISSUE TITLE
bug: revert stops machine execution without returning to parent context

### ISSUE THREAD

**Issue by greged93** [kkrt-labs/kakarot-ssj#574]
## Bug Report

**Current behavior:**

In the case of any type of error in the interpreter execution, the interpreter will fully revert the execution instead of proceeding with parent context execution.

https://github.com/kkrt-labs/kakarot-ssj/blob/40b70d379e1feb03248b4a8e2405b01d990be9e9/crates/evm/src/interpreter.cairo#L56-L62

**Expected behavior:**
A revert in a subcontext should push 0 on the stack and proceed with the parent execution.

**Comment by enitrat** [comment]
I think it's more of a missing feature than a bug: finalize revert is just implemented
https://github.com/kkrt-labs/kakarot-ssj/blob/b9f8a6d078a68ff54294d8793a2cf1b96be38d3f/crates/evm/src/interpreter.cairo#L661-L665
