### ISSUE TITLE
feat: fix coinbase implementation

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-ssj#577]
## Feature Request

fix COINBASE implementation

### Describe the Feature Request

COINBASE is an opcode that should return the receiver of the block reward
currently as Kakarot is based on a Starknet full node, we can get the sequencer address with `get_execution_info_syscall`

but we cast it into an EthAddress (since we control the sequencer we can make it so that the sequencer has a 20 bytes address). but the problem is that this address will not be "linked" by our registry to its corresponding starknet address, creating a weird behaviour should someone try to send funds to this EthAddress, here is the "faulty flow":
❌: exec_coinbase returns an eth address -> add transfer to this coinbase address -> compute starknet address of eth address  -> no known address -> lost funds

### Describe Preferred Solution

- exec_coinbase should: use `get_execution_info_syscall` to get the sequencer address, this time a starknet address, call get_evm_address() on it as if it was an EOA or a CA 
- return the received eth address 
then, 
- in the constructor of kakarot core, add an argument: initial_eoas that is a Span of Eth addresses, that may or may not be empty, in its constructor, kakarot will deploy this list of initial_eoas using its own entrypoint deploy_eoa (this part is challengeable, and may be included rather in a deployment script for kakarot, rather than forced in its constructor)
- leave this list empty for now in the test utils of deployment of kakarot, the idea is that when we have a sequencer, we will treat its account as an EOA, with a couple EthAddress and StarknetAddress, and add it in the registry at deployment of kakarot, so that at all times, coinbase is a "valid" opcode that doesn't create loopholes

**Comment by bajpai244** [comment]
@Eikix I can take this.
