### ISSUE TITLE
add memory extension costs

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-ssj#585]
Memory Expansion
During a smart contract execution, memory can be accessed with opcodes. When an offset is first accessed (either read or write), memory may trigger an expansion, which costs gas.

Memory expansion may be triggered when the byte offset (modulo 32) accessed is bigger than previous offsets. If a larger offset trigger of memory expansion occurs, the cost of accessing the higher offset is computed and removed from the total gas available at the current call context.

The total cost for a given memory size is computed as follows:
```
memory_size_word = (memory_byte_size + 31) / 32
memory_cost = (memory_size_word ** 2) / 512 + (3 * memory_size_word)
```

When a memory expansion is triggered, only the additional bytes of memory must be paid for. Therefore, the cost of memory expansion for specific opcode is thus:
```
memory_expansion_cost = new_memory_cost - last_memory_cost
```
The memory_byte_size can be obtained with opcode [MSIZE](https://www.evm.codes/#59). The cost of memory expansion triggered by [MSIZE](https://www.evm.codes/#59) grows quadratically, disincentivizing the overuse of memory by making higher offsets more costly. Any opcode that accesses memory may trigger an expansion (such as [MLOAD](https://www.evm.codes/#51), [RETURN](https://www.evm.codes/#F3) or [CALLDATACOPY](https://www.evm.codes/#37)). Use our [reference](https://www.evm.codes/) to review which opcode is capable of accessing memory. Note that opcodes with a byte size parameter of 0 will not trigger memory expansion, regardless of their offset parameters.
```[tasklist]
### Tasks
- [ ] add a way to compute the cost of memory expansion
- [ ] test the feature
```

**Comment by bajpai244** [comment]
@Eikix I can take this.
