### ISSUE TITLE
feat: add options to pre_deploy evm addresses in kakarot_core

### ISSUE THREAD

**Issue by bajpai244** [kkrt-labs/kakarot-ssj#588]
### Describe the Feature Request

[Kakarot core](https://github.com/kkrt-labs/kakarot-ssj/blob/71ddcd68561dfd6a8255f2f5adff1b32b6dd022f/crates/contracts/src/kakarot_core/kakarot.cairo) should have the option to pre_deploy a bunch of EOAs { which can be used to make sure that the coinbase address we return is actually registered with kakarot, see #581  }.

We cannot do that as of now because of [this](https://github.com/starkware-libs/cairo/issues/4488) issue in the casm runner. When this is resolved, we should implement this feature.

### Describe Preferred Solution

- refactor kakarot core [constructor](https://github.com/kkrt-labs/kakarot-ssj/blob/71ddcd68561dfd6a8255f2f5adff1b32b6dd022f/crates/contracts/src/kakarot_core/kakarot.cairo#L126) to take `Span<EthAddress>`
- loop through them in the constructor, and do `self.deploy_eoa`

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [x] Yes
- [ ] No

**Comment by bajpai244** [comment]
@TAdev0 as of now, we would have to wait till https://github.com/starkware-libs/cairo/issues/4488 is resolved, and then you can take it :)

**Comment by TAdev0** [comment]
@bajpai244  yes , I will wait for the external call in constructor to be resolved. Thank you! :)

**Comment by enitrat** [comment]
@TAdev0 we will also need to wait for scarb to release a nightly after this is merged

**Comment by TAdev0** [comment]
@enitrat thank you!

**Comment by TAdev0** [comment]
@enitrat  may i start working on this one? I guess the scarb nightly integrating the merged PR is released? thank you.

**Comment by enitrat** [comment]
@TAdev0 we had to revert back to 2.4.0 release candidates as we couldn't compile our code otherwise (breaking changes from 2.4 are not included in the nightlies, so our bug still occurs on nightlies)

But they don't have the fix included - we're looking for a solution in the next days, we might transition entirely to SN Foundry.

Until then, it's not possible but I'll ping you when it's ready

**Comment by TAdev0** [comment]
@enitrat  thanks for the quick answer. Would be great to move on with SN Foundry!

**Comment by enitrat** [comment]
@TAdev0 should be good now!
