### ISSUE TITLE
dev: investigate the upside of replacing Span<u8> to ByteArray for return_data, bytecode, and error message data structures

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-ssj#590]
Currently, we use in our codebase a lot of Span<u8>
It makes sense when we need to manipulate the data at the byte level, e.g. for the EVM Memory.

But for other data structures, e.g. static ones like bytecode or the return of eth_send_transaction, it may make more sense to manipulate a ByteArray struct (abstraction over Array<felt> that behaves like a byte array)

```[tasklist]
### Tasks
- [ ] In an exploration task, try to replace in the codebase the usage of Span<u8> by ByteArray and check the: devX + gas consumption of the change for `bytecode` (affects many opcodes), `return_data`, the return_data parameter of `eth_send_transaction`
```

**Comment by TAdev0** [comment]
@Eikix  may i try to work on this one?

**Comment by Eikix** [comment]
> @Eikix may i try to work on this one?

I think it's a bit early since we're undergoing a big refactor #604

**Comment by TAdev0** [comment]
Got it !

**Comment by TAdev0** [comment]
@Eikix  may i start working on this one? it seems the big refactor has been done?

**Comment by Eikix** [comment]
> @Eikix  may i start working on this one? it seems the big refactor has been done?

Hi @TAdev0 thanks for being patient, I think this issue isn't prio at the moment, we'll have more visibility when we can run benchmarks on the codebase and check the switch to ByteArray!

Let us try to find good issues to advance the codebase in the next few days
