### ISSUE TITLE
feat: implement 0x11 - GT opcode 

### ISSUE THREAD

**Issue by jobez** [kkrt-labs/kakarot-ssj#6]
---
since: Frontier
group: Comparison & Bitwise Logic Operations
---

*Index 1 is top of the stack. See [PUSH](https://www.evm.codes/#60).*

## Stack input

0. `a`: left side integer.
1. `b`: right side integer.

## Stack output

0. `a > b`: 1 if the left side is bigger, 0 otherwise.

## Examples

| * | Input | Output | * | * | Input | Output |
|--:|------:|-------:|--:|--:|------:|-------:|
| `1` | `10` | `1` | * | `1` | `10` | `0` |
| `2` | `9` | | * | `2` | `10` | |

## Related Kakarot 0.10 Issue
https://github.com/sayajin-labs/kakarot/issues/36  
  
[Reproduce in playground](https://www.evm.codes/playground?unit=Wei&codeType=Mnemonic&code=%27z1~9wyyz2~10w%27~yPUSH1%20z%2F%2F%20Example%20y%5Cnw~10yGT%01wyz~_).

## Error cases

The state changes done by the current context are [reverted](https://www.evm.codes/?fork=merge#FD) in those cases:
- Not enough values on the stack.

**Comment by TAdev0** [comment]
@Eikix  may i implement this opcode?

**Comment by dbejarano820** [comment]
dibs
