### ISSUE TITLE
feat: support AccessList transactions

### ISSUE THREAD

**Issue by enitrat** [kkrt-labs/kakarot-ssj#617]
- Refactor `eth_send_transaction` to receive an `EthTransaction` that is refactored to an enum
- This `EthTransaction` type has three variants with associated objects representing `LegacyTx, AccessListTx`
- Parse the encoded pre-access list into a Span<EthAddress>
- Depending on the transaction type, edit the preaccessed addresses according to the transaction type
- Edit the intrinsic cost depending on the transaction type: #584

**Comment by bajpai244** [comment]
@enitrat as discussed, I am taking this.
