### ISSUE TITLE
feat(gas): prepare call gas calculations

### ISSUE THREAD

**Issue by enitrat** [kkrt-labs/kakarot-ssj#624]
## Feature Request
- Calculate the MessageCallGas (cost and stipend) for executing call Opcodes.
- Return this value from the `prepare_call` function
- Charge gas accordingly in call opcodes

**Comment by bajpai244** [comment]
@enitrat I am taking this one.

**Comment by enitrat** [comment]
@bajpai244 I just noticed I go confused and opened a duplicate #645
