### ISSUE TITLE
feat: implement blake2f (0x09) precompile

### ISSUE THREAD

**Issue by bajpai244** [kkrt-labs/kakarot-ssj#662]
### Describe the Feature Request

Implement the [blake2f(0x09)](https://www.evm.codes/precompiled#0x09?fork=shanghai) precompile.

### Additional Context

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [x] Yes
- [ ] No

**Comment by TAdev0** [comment]
Hey @bajpai244  @enitrat, Is anyone assigned to this precompile? If not, may i be assigned and give it a try?
