### ISSUE TITLE
feat(gas): implement gas refund mechanism

### ISSUE THREAD

**Issue by enitrat** [kkrt-labs/kakarot-ssj#683]
## Feature Request

Implement gas refunds mechanisms of the EVM. The gas refunds will be reimbursed to the user after processing the transaction.

### Additional Context

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [ ] Yes
- [ ] No

**Comment by TAdev0** [comment]
@enitrat may I work on this feature this week or did you plan to self assign? 
Merry Christmas by the way :)

**Comment by enitrat** [comment]
@TAdev0 I'll take it as it's the last step for gas mechanism and quite complex
