### ISSUE TITLE
feat: add gas_used in the eth_call return data if possible 

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-ssj#696]
## Feature Request

Linked to https://github.com/kkrt-labs/kakarot/issues/870

#Describe the Feature Request
Since we're aiming to charge EVM gas, we need to be able to estimate EVM gas.
Currently, our gas accounting works, and so, for the eth_estimateGas route, we need to be able to query how much gas a tx will take.
We could: run the eth_call corresponding to what the tx would be, and return the gas_used of that.

Implementation:
Change the eth_call return format to additionally give the gas_used in the transaction.

**Comment by enitrat** [comment]
```
        fn eth_call(
            self: @ContractState, origin: EthAddress, tx: EthereumTransaction
        ) -> (bool, Span<u8>) {
            if !self.is_view() {
                panic_with_felt252('fn must be called, not invoked');
            };

            let origin = Address { evm: origin, starknet: self.compute_starknet_address(origin) };

            let TransactionResult{success, return_data, gas_used: _, state: _ } = self
                .process_transaction(origin, tx);

            (success, return_data)
        }
 ```
 
 gas_used is already here, just need to update the interface ;)
