### ISSUE TITLE
feat: implement 0x12 - SLT opcode

### ISSUE THREAD

**Issue by jobez** [kkrt-labs/kakarot-ssj#7]
---
fork: Frontier
group: Comparison & Bitwise Logic Operations
---

*Index 1 is top of the stack. See [PUSH](https://www.evm.codes/#60).*

## Notes

All values are treated as two's complement signed 256-bit integers.

## Stack input

0. `a`: left side signed integer.
1. `b`: right side signed integer.

## Stack output

0. `a < b`: 1 if the left side is smaller, 0 otherwise.

## Examples

| * | Input | Output | * | * | Input | Output |
|--:|------:|-------:|--:|--:|------:|-------:|
| `1` | `0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF` | `1` | * | `1` | `10` | `0` |
| `2` | `0` | | * | `2` | `10` | |

[Reproduce in playground](https://www.evm.codes/playground?unit=Wei&codeType=Mnemonic&code='y1z9v32%200xsssstwwy2z10z10t'~uuuuzv1%20y%2F%2F%20Example%20w%5CnvwPUSHuFFtwSLTs~~%01stuvwyz~_).

## Error cases

The state changes done by the current context are [reverted](https://www.evm.codes/?fork=merge#FD) in those cases:
- Not enough values on the stack.

**Comment by khaeljy** [comment]
@Eikix Can I implement this OPCODE?

**Comment by Eikix** [comment]
Can you:
- check if there is an official implementation of this in the starknet u256 lib?
- if there isnt a starknet official lib for it, create a small library (take reference on bitwise, and exponentiation for good practices) for signed comparison (slt and sgt) and put it in math.cairo in the util crate and test it unitarily? (if sgt is already taken, then try to pair program with the person to make sure you can help each other on this library)
- then use this library in the opcode implem

**Comment by khaeljy** [comment]
I couldn't find anything in the Starknet lib, so I created a Trait `SignedPartialOrd`.
Is it what you wanted?

**Comment by khaeljy** [comment]
I couldn't find anything in the Starknet lib, so I created a Trait `SignedPartialOrd`.
Is it what you wanted?
