### ISSUE TITLE
bug: is_account_alive

### ISSUE THREAD

**Issue by enitrat** [kkrt-labs/kakarot-ssj#707]
## Bug Report

**Kakarot version:**

**Current behavior:**
Reads the local state to check whether an account is alive or not - returns false if the account is not in the local state, meaning not cached during the transaction

**Expected behavior:**
Should return `false` only if the account doesn't exist _at all_, meaning has no code, nonce nor balance _in the global state_

**Comment by TAdev0** [comment]
@enitrat  isn't it already the case?

```
 fn is_account_alive(ref self: State, evm_address: EthAddress) -> bool {
        let account = self.accounts.read(evm_address.into());
        match account {
            Option::Some(acc) => {
                return !(acc.nonce == 0 && acc.code.len() == 0 && acc.balance == 0);
            },
            Option::None => { return false; }
        }
    }
    ```

the function checs for nonce, codesize and balance. But i guess the ref self is a local state right? how can we grab the global state?

**Comment by TAdev0** [comment]
does it mean kakarot core storage needs to be modified, to store all Account structs for all ethAddress in it?

**Comment by enitrat** [comment]
if you call `get_account` you will get an account object that reflects its "true" state at the current time, not only the cached one

**Comment by TAdev0** [comment]
oh yeah i get it, with `fetch_or_create` , you reconstruct the Account struct corresponding to the evm_address

**Comment by TAdev0** [comment]
why? if you call `get_account`,  the return value is `self.accounts.read(evm_address.into()).unwrap()` if it is in the cache,
and `is_account_alive` does the same

**Comment by TAdev0** [comment]
@enitrat  ok its all clear now. Spent time to understand how bytecode and nonce were stored in contracts, using low level methods.
