### ISSUE TITLE
dev: make all loops counters felt-based

### ISSUE THREAD

**Issue by enitrat** [kkrt-labs/kakarot-ssj#717]
https://twitter.com/shrameetweets/status/1751608987223507393?t=MF831MPVIJO0zhBxCYAQ3g&s=19

Make all loop counter felt-based and prefer pop_front to read sequentially

**Comment by remybar** [comment]
Interesting ! I will have a look at this one :)

**Comment by enitrat** [comment]
hmm, I'd rather not, it was just a post it to remember but I'd like to avoid optimizations before we have 100% cleared ef-tests

**Comment by remybar** [comment]
> hmm, I'd rather not, it was just a post it to remember but I'd like to avoid optimizations before we have 100% cleared ef-tests

Ok, no problem 🫡
So it's better to wait for the end of these tests before contributing on issues ?

**Comment by enitrat** [comment]
irrelevant with stwo / native.
