### ISSUE TITLE
bug: `SAR` opcode panics if the shift is greater than the type size

### ISSUE THREAD

**Issue by enitrat** [kkrt-labs/kakarot-ssj#726]
## Bug Report

The result should be 0 if the shift is greater than the type size, so we should use `wrapping_shr`

**Comment by remybar** [comment]
Do you talk about the `exec_sar()` function implementing the `SAR` opcode ?

There are several tests which validate that `0` (if `value` is positive) or `-1` (if `value` is negative) is returned if more than 256 bits have to be shifted and I don't see any panic when executing them 🤔 

But I probably missed something 😅

**Comment by enitrat** [comment]
> if more than 256 bits have to be shifted and I don't see any panic when executing them 🤔

I think the problem is if shift==256. But even then, SAR should use wrapping instead of panicking shift, because the EVM doesn't have this panicking semantic
