### ISSUE TITLE
dev: Rename `Precompiles` class to `Cairo1Helpers`

### ISSUE THREAD

**Issue by enitrat** [kkrt-labs/kakarot-ssj#738]
We will expand the range of features provided by this class, so that we can benefit from other Cairo 1 features as well in Cairo Zero: 
block_hash syscall, keccak_syscall, etc

**Comment by remybar** [comment]
Hi @enitrat 👋 

Could I work on this task ? I would like to work on a project in Cairo and it seems that you have several tasks to do here :-)

**Comment by enitrat** [comment]
sure, go ahead
