### ISSUE TITLE
feat: validate that an eoa has empty bytecode

### ISSUE THREAD

**Issue by enitrat** [kkrt-labs/kakarot-ssj#745]
can be done in `__validate__`, see https://github.com/kkrt-labs/kakarot/pull/982

**Comment by TAdev0** [comment]
@enitrat  I can work on it today if its available to grab

**Comment by enitrat** [comment]
It might have been solved with the merge of accounts I will check

**Comment by TAdev0** [comment]
oh yeah indeed I havent checked:

```
            assert(self.Account_bytecode.read().len().is_zero(), 'EOAs: Cannot have code');
```
