### ISSUE TITLE
feat: use sha256 syscall

### ISSUE THREAD

**Issue by enitrat** [kkrt-labs/kakarot-ssj#753]
### Describe the Feature Request

Use the sha256 syscall internally and expose it as a library call in Cairo1Helpers.

ref: https://github.com/starkware-libs/cairo/pull/5348

**Comment by enitrat** [comment]
it's not available yet

**Comment by Akashneelesh** [comment]
Got it, ones it is merged.

**Comment by enitrat** [comment]
Will probably need to wait for a proper release and we will need to decide on our end when we bump our dependency

**Comment by enitrat** [comment]
Will probably need to wait for a proper release and we will need to decide on our end when we bump our dependency

**Comment by Akashneelesh** [comment]
> Will probably need to wait for a proper release and we will need to decide on our end when we bump our dependency

Understood, thanks.
