### ISSUE TITLE
feat: add RIP-7212 to the list of precompiles Cairo1Helpers module

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-ssj#755]
### Describe the Feature Request

The people demand [RIP-7212](https://ethereum-magicians.org/t/eip-7212-precompiled-for-secp256r1-curve-support/14789)! 

What RIP7212: https://www.alchemy.com/blog/what-is-rip-7212
Why: for easier usage of TEE signer
How: use the new shiny Starknet secp256r1 syscall!

### Describe Preferred Solution

- Go through the EIP -> https://eips.ethereum.org/EIPS/eip-7212 and RIP -> https://github.com/ethereum/RIPs/blob/master/RIPS/rip-7212.md to understand the API of the precompile, the gas usage and its permanent address.
- Go through the documentation of the secp256r1 syscall in Starknet
- Implement the precompile
- Test the precompile

Difficulty level: intermediate
Estimated time: 1 day of reading, 1 day of implem, 1 day of back and forth with maintainers

**Comment by Quentash** [comment]
Hello,
I could try to take care about this ticket !
