### ISSUE TITLE
feat: migrate to starknet-foundry

### ISSUE THREAD

**Issue by enitrat** [kkrt-labs/kakarot-ssj#756]
### Describe the Feature Request
 
Starknet Foundry now has compelling features justifying a transition from the native Cairo test runner to SN Foundry (fuzzing, profiling, resources estimations, etc).

Make the transition to Starknet Foundry

### Additional Context

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [ ] Yes
- [ ] No

**Comment by TAdev0** [comment]
@enitrat may I be assigned to this issue?

**Comment by enitrat** [comment]
I think it's going to be too complex, will need to see what a correct approach would be
