### ISSUE TITLE
dev: use `Deref` to trivially access `T`'s members from `Box<T>`

### ISSUE THREAD

**Issue by enitrat** [kkrt-labs/kakarot-ssj#808]
Current architecture will use some more `Box<T>` types to pass big structs to functions and reduce the step usage. By implementing Deref<Box<T>> and DerefMut<Box<T>> with T being the internal target type we could abstract the `var.unbox().member` accesses and simply do `var.member`, where `var: Box<T>`.

Also use for all Nullables

**Comment by remybar** [comment]
Can I have a look at this task ?
