### ISSUE TITLE
dev: migrate to `for` and `while` loop syntaxes

### ISSUE THREAD

**Issue by enitrat** [kkrt-labs/kakarot-ssj#809]
Where possible and when we can migrate to 2.7 (depending on Cairo-Native), migrate loops to, where possible, for and while syntax.

**Comment by quentin-abei** [comment]
Are you accepting contribution ?

**Comment by enitrat** [comment]
yes but this is not a priority for us so it might take a while for us to review / merge

**Comment by quentin-abei** [comment]
Please assign

**Comment by quentin-abei** [comment]
Ok , I will start work on this Monday .

**Comment by enitrat** [comment]
I think it will take us a while to update to 2.7 depending on cairo-native, so it's not sure when this can start

**Comment by quentin-abei** [comment]
No problem, I will monitor the issues
