### ISSUE TITLE
feat: support SNIP-9 on account contracts

### ISSUE THREAD

**Issue by enitrat** [kkrt-labs/kakarot-ssj#819]
See https://github.com/kkrt-labs/kakarot/blob/7fb90d799a5a0bfab0a48bdfcb4e867d35b4943c/src/kakarot/accounts/account_contract.cairo#L83

**Comment by remybar** [comment]
Can I work on this ?

Some info I found: 
- SNIP-9 : https://community.starknet.io/t/snip-outside-execution/101058
- Argent implementation: https://github.com/argentlabs/argent-contracts-starknet/tree/main/src/outside_execution

**Comment by enitrat** [comment]
yes, and the reference implementation in Cairo Zero: https://github.com/kkrt-labs/kakarot/blob/7fb90d799a5a0bfab0a48bdfcb4e867d35b4943c/src/kakarot/accounts/account_contract.cairo#L83

**Comment by enitrat** [comment]
@remybar how are things going?

**Comment by remybar** [comment]
> @remybar how are things going?

Hi @enitrat 
We finally took some holidays until end of August so I'll be back to work on issues end of August/beginning of September.

Do you need this feature earlier than that? If yes, I can push what I did if someone wants to continue.

**Comment by enitrat** [comment]
yes please!

**Comment by remybar** [comment]
> yes please!

I pushed what I've started in the following PR https://github.com/kkrt-labs/kakarot-ssj/pull/836.

Sorry for the delay, I don't like to start a task and let it for several days/weeks 😕
