### ISSUE TITLE
feat: add `get_code_hash` / `set_code_hash` entrypoints to the account class

### ISSUE THREAD

**Issue by enitrat** [kkrt-labs/kakarot-ssj#829]
## Feature Request
see https://github.com/kkrt-labs/kakarot/blob/main/src/kakarot/accounts/library.cairo#L464
- Create the storage variable
- Expose `get`/`set` accessors
### Additional Context

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [ ] Yes
- [ ] No

**Comment by chachaleo** [comment]
Can I take this ? :)
