### ISSUE TITLE
feat: store codehash upon deployment and read codehash from storage in `fetch_or_create`

### ISSUE THREAD

**Issue by enitrat** [kkrt-labs/kakarot-ssj#840]
## Feature Request

Store the codehash in storage upon account deployment, and read it / cache it in `fetch_or_create` to avoid re-computations of code hashes.

References:
- https://github.com/kkrt-labs/kakarot/blob/65e333a0d3475e81b0a6367b0f00561c763da0a0/src/kakarot/accounts/library.cairo#L432-L436
- https://github.com/kkrt-labs/kakarot/blob/65e333a0d3475e81b0a6367b0f00561c763da0a0/src/kakarot/accounts/library.cairo#L438-L443
https://github.com/kkrt-labs/kakarot/blob/65e333a0d3475e81b0a6367b0f00561c763da0a0/src/kakarot/library.cairo#L330-L339

### Additional Context

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [ ] Yes
- [ ] No

**Comment by faytey** [comment]
I would love to work on this issue
