### ISSUE TITLE
feat: implement `BLOBBASEFEE`

### ISSUE THREAD

**Issue by enitrat** [kkrt-labs/kakarot-ssj#852]
Blobbasefee will simply charge gas and push 0 on the stack.

- Reference: https://github.com/kkrt-labs/kakarot/blob/65e333a0d3475e81b0a6367b0f00561c763da0a0/src/kakarot/instructions/block_information.cairo#L135-L138

**Comment by adrianvrj** [comment]
Hey can I work on this?
