### ISSUE TITLE
dev: use constants for precompiles addresses range

### ISSUE THREAD

**Issue by enitrat** [kkrt-labs/kakarot-ssj#859]
use constants instead of inlined numbers for the precompiles address range.

https://github.com/kkrt-labs/kakarot-ssj/blob/041acc93944cd2fa2b24f6f00a45c91d83414d46/crates/evm/src/model.cairo#L138-L143

reference:

https://github.com/kkrt-labs/kakarot/blob/65e333a0d3475e81b0a6367b0f00561c763da0a0/src/kakarot/precompiles/precompiles_helpers.cairo#L1-L37

**Comment by lprovenzano** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/kakarot-zkevm).

### My background and how it can be leveraged
Hello, my name is Luca! I have been a backend software engineer for over 8 years. It would be a pleasure to collaborate with you, especially on this issue. I started studying Web3 development a few months ago and would like to contribute. 
Thank you for considering me.

### How I plan on tackling this issue
I will analyze the project and take the reference to be able to solve the problem.

**Comment by enitrat** [comment]
#868
