### ISSUE TITLE
dev: remove duplicated files

### ISSUE THREAD

**Issue by obatirou** [kkrt-labs/kakarot-ssj#878]
At some point it was not possible to import files from tests in src hence duplicate files were created. For example: 
* https://github.com/kkrt-labs/kakarot-ssj/blob/main/crates/contracts/tests/test_utils.cairo
* https://github.com/kkrt-labs/kakarot-ssj/blob/main/crates/contracts/src/test_utils.cairo

Verify this is now resolved and remove those duplicated files.

**Comment by ScottyDavies** [comment]
@obatirou can I please be assigned this task ?
