### ISSUE TITLE
feat: implement 0x14 - EQ opcode

### ISSUE THREAD

**Issue by jobez** [kkrt-labs/kakarot-ssj#9]
---
fork: Frontier
group: Comparison & Bitwise Logic Operations
---

*Index 1 is top of the stack. See [PUSH](https://www.evm.codes/#60).*

## Stack input

0. `a`: left side integer.
1. `b`: right side integer.

## Stack output

0. `a == b`: 1 if the left side is equal to the right side, 0 otherwise.

## Examples

| * | Input | Output | * | * | Input | Output |
|--:|------:|-------:|--:|--:|------:|-------:|
| `1` | `10` | `1` | * | `1` | `10` | `0` |
| `2` | `10` | | * | `2` | `5` | |

[Reproduce in playground](https://www.evm.codes/playground?unit=Wei&codeType=Mnemonic&code='z1~10wyyz2~5w'~yPUSH1%20z%2F%2F%20Example%20y%5Cnw~10yEQ%01wyz~_).

## Error cases

The state changes done by the current context are [reverted](https://www.evm.codes/?fork=merge#FD) in those cases:
- Not enough values on the stack.

**Comment by TAdev0** [comment]
@Eikix  may i implement this opcode?

**Comment by Alextnetto** [comment]
I'm doing this!! Will submit PR soon.

**Comment by danilowhk** [comment]
@Alextnetto

**Comment by khaeljy** [comment]
Can I take this?

**Comment by Alextnetto** [comment]
Hey! Sorry for the delay on the correction, submitting a new commit with the code fixed and tested. Lmk if I can do anything else on this Issue!

**Comment by Alextnetto** [comment]
@enitrat, It would be great to understand more about your suggestion [here](https://github.com/kkrt-labs/kakarot-ssj/pull/223/files/ddd51b1146b9a6a57c302899707cf816f0fbe7a8#r1308096985). 
It's better to revert immediately if it isn't `Option<T>`, right?

**Comment by Eikix** [comment]
Important update: we are gathering some bugs in the [Kakarot v0 codebase](https://github.com/kkrt-labs/kakarot), we need to make sure each issue and each PR in Kakarot-ssj is aware of the lists of known bugs. Look at [this tracking issue](https://github.com/kkrt-labs/kakarot-ssj/issues/324) everytime you take an issue and check your issue isn't targeted by a known bug. Will add this reminder in many places to make sure we keep track of known bugs.

**Comment by enitrat** [comment]
> @enitrat, It would be great to understand more about your suggestion [here](https://github.com/kkrt-labs/kakarot-ssj/pull/223/files/ddd51b1146b9a6a57c302899707cf816f0fbe7a8#r1308096985). 
> It's better to revert immediately if it isn't `Option<T>`, right?

No, we want to return a result T type and handle gracefully the eventual error later

**Comment by Alextnetto** [comment]
Okay, thanks @enitrat! 

I was comparing it with the other functions implemented in my branch. [This](https://github.com/kkrt-labs/kakarot-ssj/commit/743ed6bd085adf5afe1f201013ac3668c1c0b3a2) commit fix it.
