### ISSUE TITLE
dev: prefer `from_be_bytes` to `load_word`

### ISSUE THREAD

**Issue by enitrat** [kkrt-labs/kakarot-ssj#906]
`from_be_bytes` is a generic implementation that tries converting a collection of bytes to a type T.

Refactor the codebase to use `from_be_bytes` and `from_be_bytes_partial` instead of `load_word` for better maintainability.

**Comment by enitrat** [comment]
<img width="657" alt="image" src="https://github.com/user-attachments/assets/b79fbc8c-6a39-43f8-9dd6-a91ca954f657">
<img width="592" alt="image" src="https://github.com/user-attachments/assets/b6108d51-9275-4a06-8d7d-3cd0a4eac9c8">

**Comment by mubarak23** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/kakarot-zkevm).

### My background and how it can be leveraged
I am a Experience Cairo smart contract developer with experience working on projects such as Just Art Peace, Dojo, Kart, TBA, and Shinigami. Before transitioning to Cairo development, I was a backend developer specializing in Rust.



My recent work with cairo starknet
- https://github.com/keep-starknet-strange/raito/pull/128
- https://github.com/keep-starknet-strange/raito/pull/143
- https://github.com/horuslabsio/TBA/pull/45
- https://github.com/horuslabsio/karst-core/pull/60
- https://github.com/keep-starknet-strange/art-peace/pull/121
- https://github.com/keep-starknet-strange/zkramp/pull/33
- https://github.com/keep-starknet-strange/art-peace/pull/32
- https://github.com/horuslabsio/TBA/pull/53



My recent work with rust
- https://github.com/mubarak23/axum-user-auth
- https://github.com/antoyo/rustc_codegen_gcc/pull/1
- https://github.com/antoyo/rustc_codegen_gcc/pull/5
- https://github.com/fedimint/fedimint/pull/5994
- https://github.com/mubarak23/soroban-bank



### How I plan on tackling this issue
I estimate this will take 16hrs to complete.

This is how I would tackle this issue:
- Locating all ceil32(size) in the codebase
- Replace it with 32bytes_words_size function 
- Make sure  scare build 
- Write unit test where needed

**Comment by guha-rahul** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/kakarot-zkevm).

### My background and how it can be leveraged
Being a cairo dev and a newcomer to the kakarot codebase , i think this will be a good issue to get familiar with the codebase. 

### How I plan on tackling this issue
1. Go through the entire codebase
2.locate where from_be_bytes is located and replace that with from_be_bytes_partial along with other changes that are required!

**Comment by lordshashank** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/kakarot-zkevm).

### My background and how it can be leveraged
Hi, I have been contributing in odhacks for quite some time now and have expertise in rust and blockchain specs , few of them are 
- Contributed to Floresta as Summer of Bitcoin 2024 fellow
- contributed to RUst lang's codegen GCC and implemented new traits and tests.
- Contributed to starknet rust devnet in odhack

### How I plan on tackling this issue
I will search for possible usecases of `from_be_bytes` and `from_be_bytes_partial` in codebase and replace `load_word` with them for better practices and maintainability
I will ensure all the tests pass without breaking anything.
