### ISSUE TITLE
feat: add `eth_chain_id` entrypoint

### ISSUE THREAD

**Issue by enitrat** [kkrt-labs/kakarot-ssj#923]
- Add an `eth_chain_id` entrypoint to the `KakarotCore` contract
- This entrypoint will return the `chain_id` field of the `tx_info`, modulo `2**53`
- Replace all references to tx_info.chain_id by this value returned from the Kakarot Contract

Closes #920

**Comment by bitfalt** [comment]
hii! Is this issue open for contributors? If so I'd love to tackle this issue. I assume I would need to use `get_tx_info().unbox()` and then return the `chain_id` field after applying modulo `2**53`, then refactor the code with the value returned from it.

**Comment by enitrat** [comment]
Hi! Yes, you can do it.

To help you, here's an existing implementation in old cairo.

https://github.com/kkrt-labs/kakarot/blob/7a83ddf6cfb7a69d995245291fe11c1d2444e408/src/kakarot/library.cairo#L124-L131

You could generally just find and replace all occurences of use of this tx_info.chain_id by a call to this function

**Comment by bitfalt** [comment]
Okay! Thank you so much for providing a link to the existing implementation, will start ASAP!
