### ISSUE TITLE
feat: emit event on transaction execution

### ISSUE THREAD

**Issue by enitrat** [kkrt-labs/kakarot-ssj#925]
Inside the `execute_from_outside` function, we should emit an event when a transaction is executed.
See [Argent account](https://github.com/argentlabs/argent-contracts-starknet/blob/1352198956f36fb35fa544c4e46a3507a3ec20e3/src/presets/user_account.cairo#L211-L213):

See [KakarotZero](https://github.com/kkrt-labs/kakarot/blob/7a83ddf6cfb7a69d995245291fe11c1d2444e408/src/kakarot/accounts/library.cairo#L224-L227)

**Comment by EmmanuelAR** [comment]
Heyyy @enitrat  im Emmanuel, software dev from Costa Rican and Dojo Coding 
can i work on this? I will add the new event when the transaction is execute, let me know!!

**Comment by enitrat** [comment]
Actually it was done in https://github.com/kkrt-labs/kakarot-ssj/pull/927, thanks
