### ISSUE TITLE
feat: use `get_starknet_address`

### ISSUE THREAD

**Issue by enitrat** [kkrt-labs/kakarot-ssj#928]
- `compute_starknet_address` returns the value computed for an EVM address based on the uninitialized class hash
- `address_registry` returns the value stored in the Kakarot_evm_to_starknet_address storage var

We introduced in KakarotZero a `get_evm_address` entrypoint that reads the address registry, and if no entry, computes the evm address.

Use it throughout the codebase instead of `compute_starknet_address`.

**Comment by adrianvrj** [comment]
hey @enitrat do you need help with this one?
