### ISSUE TITLE
feat: implement `eth_get_balance`

### ISSUE THREAD

**Issue by enitrat** [kkrt-labs/kakarot-ssj#941]
Implement the method `eth_get_balance` of the `EthRPC` trait

https://github.com/kkrt-labs/kakarot-ssj/blob/b1f7f8c13be38edc081f0738c188561240c098b4/crates/contracts/src/kakarot_core/eth_rpc.cairo#L124-L126

Given an evm address, this will return the balance of this address.

Use this where required inside the codebase, e.g.

https://github.com/kkrt-labs/kakarot-ssj/blob/b1f7f8c13be38edc081f0738c188561240c098b4/crates/evm/src/backend/validation.cairo#L52-L56

https://github.com/kkrt-labs/kakarot-ssj/blob/b1f7f8c13be38edc081f0738c188561240c098b4/crates/evm/src/backend/starknet_backend.cairo#L120-L125

**Comment by stevencartavia** [comment]
Hi, I would like to work on this!

**Comment by enitrat** [comment]
Hi, this will be for the ODHack week

**Comment by bitfalt** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/kakarot-zkevm).

### My background and how it can be leveraged
Hii! My name is Daniel, I’m a Computer Science student and web3 developer. I’ve done some contributions, finished a Starknet Bootcamp, exercises on NodeGuardians, finished Starklings and I have participated in multiple Hackathons. I’m also a member of the Dojo Coding community.I’ve contributed to the project in the past.

### How I plan on tackling this issue
I would approach this issue in the following way:
- Create the implementation for the eth_get_balance
- Refactor the code to import the EthRPC trait properly (i’ve already done it in the past contribution)
- Refactor the codebase to call eth_get_balance where it is necessary
- I would ask the maintainers if any questions come up during my implementation

**Comment by manlikeHB** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/kakarot-zkevm).

### My background and how it can be leveraged
Hi, I am Cairo dev with lots of experience contributing to Cairo projects, my OD profile is a witness to this. This feat is right within my comfort zone.

### How I plan on tackling this issue
I would go through the code base and understand the functionality expected, after that I would write a robust test ensuring all test cases are covered and the feat behaves as expected.

**Comment by mahesh-dalle** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/kakarot-zkevm).

### My background and how it can be leveraged
I am a cairo developer , and have a thorough understanding of ethereum rpc endpoints

### How I plan on tackling this issue
Read the codebase, try to implement the rpc endpoint , use the implementation where its needed.

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/kakarot-zkevm).

### My background and how it can be leveraged
i am a blockchain developer

### How I plan on tackling this issue
I will imlpement the following:

1. Define Method: Implement the `eth_get_balance` logic in `kakarot_core/eth_rpc.cairo` to fetch the balance for a given EVM address.
2. Integrate: Use this method where required in the codebase, such as in `validation.cairo` and `starknet_backend.cairo` by replacing or linking it with balance retrieval logic.
3. Testing: Ensure the method is correctly fetching balances and integrate test cases to validate its functionality

**Comment by JoE11-y** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/kakarot-zkevm).

### My background and how it can be leveraged
With over four years in blockchain and backend development, I’ve worked across different ecosystems, handling everything from smart contract design to on-chain interactions and protocol integration. I focus on building secure, scalable, and reliable blockchain applications, managing both on-chain and off-chain infrastructure.

### How I plan on tackling this issue
As this would be my first contribution. I'd start by reviewing Kakarot's architecture, then select the best possible way for implementing the eth_get_rpc. Once completed would proceed to test and integrate with the JSON rpc interface.

**Comment by saimeunt** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/kakarot-zkevm).

### My background and how it can be leveraged
I have some experience in Cairo, mostly porting Solidity ERCs to Cairo:
https://github.com/carbonable-labs/cairo-erc-7496
https://github.com/carbonable-labs/cairo-erc-7498

### How I plan on tackling this issue
I will leverage kakarot_core address_registry function to map the given EthAddress to the corresponding Starknet ContractAddress, then I will query this address balance on the native_token.
I will search for all occurences in the codebase where accessing the eth balance is needed and refactor using the EthRPC dispatcher.
