### ISSUE TITLE
feat: implement `eth_get_transaction_count`

### ISSUE THREAD

**Issue by enitrat** [kkrt-labs/kakarot-ssj#942]
https://github.com/kkrt-labs/kakarot-ssj/blob/b1f7f8c13be38edc081f0738c188561240c098b4/crates/contracts/src/kakarot_core/eth_rpc.cairo#L128-L130

Given an evm address, this will return the transaction count (none) of this address.

Use it where required in the codebase, for example:

https://github.com/kkrt-labs/kakarot-ssj/blob/b1f7f8c13be38edc081f0738c188561240c098b4/crates/evm/src/backend/validation.cairo#L35-L38

reference:

https://github.com/kkrt-labs/kakarot/blob/main/src/kakarot/eth_rpc.cairo#L43-L50

**Comment by Gerson2102** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/kakarot-zkevm).

### My background and how it can be leveraged
---

### Hey! I'm Gerson. 👋

Member of **Dojo Coding**. I have contributed before to other Kakarot projects like:

- `kakarot-rpc`
- `ef-tests`

Can I work on this issue?

Check my OnlyDust profile, I've contributed to many projects: [Profile](https://app.onlydust.com/u/Gerson2102)



### How I plan on tackling this issue
---

### Plan to Solve the Issue:

1. **Study the codebase** to understand the current structure and functionality.
2. **Understand the problem** that needs to be solved by thoroughly reading the issue details.
3. **Leverage all provided resources** within the issue to get a better grasp of the task at hand.
4. If I encounter roadblocks, I will **ask questions ASAP** in the Telegram group to move forward effectively.
5. **I will open a PR** and wait for ur feedback

---

**Comment by mubarak23** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/kakarot-zkevm).

### My background and how it can be leveraged
I am a Experience Cairo smart contract developer with experience working on projects such as Just Art Peace, Dojo, Kart, TBA, and Shinigami. Before transitioning to Cairo development, I was a backend developer specializing in Rust.



My recent work with cairo starknet
- https://github.com/keep-starknet-strange/raito/pull/128
- https://github.com/keep-starknet-strange/raito/pull/143
- https://github.com/horuslabsio/TBA/pull/45
- https://github.com/horuslabsio/karst-core/pull/60
- https://github.com/keep-starknet-strange/art-peace/pull/121
- https://github.com/keep-starknet-strange/zkramp/pull/33
- https://github.com/keep-starknet-strange/art-peace/pull/32
- https://github.com/horuslabsio/TBA/pull/53



My recent work with rust
- https://github.com/mubarak23/axum-user-auth
- https://github.com/antoyo/rustc_codegen_gcc/pull/1
- https://github.com/antoyo/rustc_codegen_gcc/pull/5
- https://github.com/fedimint/fedimint/pull/5994
- https://github.com/mubarak23/soroban-bank


### How I plan on tackling this issue
Am going to
-  implement the function 
- Look through the codebase where ever the function is call and make sure the code build successfully
- Write unit test for the function
ETH: 18hrs

**Comment by mubarak23** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/kakarot-zkevm).

### My background and how it can be leveraged
I am a Experience Cairo smart contract developer with experience working on projects such as Just Art Peace, Dojo, Kart, TBA, and Shinigami. Before transitioning to Cairo development, I was a backend developer specializing in Rust.



My recent work with cairo starknet
- https://github.com/keep-starknet-strange/raito/pull/128
- https://github.com/keep-starknet-strange/raito/pull/143
- https://github.com/horuslabsio/TBA/pull/45
- https://github.com/horuslabsio/karst-core/pull/60
- https://github.com/keep-starknet-strange/art-peace/pull/121
- https://github.com/keep-starknet-strange/zkramp/pull/33
- https://github.com/keep-starknet-strange/art-peace/pull/32
- https://github.com/horuslabsio/TBA/pull/53



My recent work with rust
- https://github.com/mubarak23/axum-user-auth
- https://github.com/antoyo/rustc_codegen_gcc/pull/1
- https://github.com/antoyo/rustc_codegen_gcc/pull/5
- https://github.com/fedimint/fedimint/pull/5994
- https://github.com/mubarak23/soroban-bank


### How I plan on tackling this issue
Am going to
-  implement the function 
- Look through the codebase where ever the function is call and make sure the code build successfully
- Write unit test for the function
ETH: 18hrs
